### ISSUE TITLE
SMW 3.0 Remove depreciated function, class task list

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1014]
List potential functions, classes, or marked `FIXED` comments to be removed with SMW 3.0 to make use of the semver "make incompatible API changes" [0] policy.
- It is expected that SMW 3.0 no longer supports MW 1.19 to 1.26 therefore remove all code that was introduced as compatibility layer 
- #698 / It is expected that SMW 3.0 requires at least PHP 5.4 (or PHP 5.5) therefore check callbacks/Closure for potential improvement in the `use` (local vs `$this`)
## List of
- [x] 1 Remove depreciated SEMANTIC_EXTENSION_TYPE / Flag used to indicate SMW defines a semantic extension type for extension credits, now provieded by MW core. [See also](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/SemanticMediaWiki.php#L116)
- [x] 2 Remove support for the "type" namespace #399
- [x] 3 Remove `SMW_conceptCache.php`, `SMW_dumpRDF.php`, `SMW_refreshData.php`, `SMW_setup.php` see #2789
- [x] 4 Remove deprecated functions from `SMW\DIProperty` (see `SMW\PropertyRegistry`)
- [x] 5 Remove deprecated functions from `SMW\DataValueFactory` (see `SMW\DataTypeRegistry`)
- [x] 6 Remove `Special:SemanticStatistics` (see `Special:Statistics` for providing the information)
- [x] 7 `SMWDataValue::prepareValue`, see https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1061#issuecomment-145354555
- [x] 8 Remove old $wgSpecialPageGroups, see #1214
- [x] 9 Replace usages of Revision::getRawText #1371

**These are definitely not used by SMW itself**:
- [x] Remove `ResultPrinter::m_params`
- [x] Remove `ResultPrinter::textDisplayParameters`
- [x] Remove `ResultPrinter::exportFormatParameters`
- [x] Remove `SMWQueryProcessor::processFunctionParams`
- [x] Remove `SMWQueryProcessor::getResultFromFunctionParams`
- [x] Remove `SMWQueryProcessor::getResultFromQueryString`
- [x] Remove `SMWResultArray::getNextObject`
- [x] Remove `SMWJsonResultPrinter` class_alias
- 
## Notes

[0] http://semver.org/

```
wget http://get.sensiolabs.org/php-cs-fixer.phar
php php-cs-fixer.phar fix src/ --fixers=short_array_syntax
```

**Comment by mwjames** [comment]
@JeroenDeDauw @kghbln I made this into a 3.0 task list to get all old cruft removed otherwise trying to do this without a list will be pain. It further allows users/developers of extensions to track API changes more visibly before changes are made. 

If you find a comment in the source, just list them here for reference.

**Comment by mwjames** [comment]
Remove the `Title` object usage from `SQLStore` and `SPARQLStore` which requires some changes to its public methods (`delete` / `changeTitle` etc.) and encapsulate it with `DIWikiPage` instead.

**Comment by joelkp** [comment]
Here's additional things found by grepping the SMW source for "deprecated", "vanish" and "Vanish". At first I included the deprecation messages (many of which called for removal in 1.7, 1.10, etc.), but it grew rather long. So I boiled it down to the below list by topic.

Hope you find it useful - I thought this might be a simple contribution to make.

## Classes
- `SMWParamFormat` (includes/params/SMW_ParamFormat.php)

## Class aliases:
- Remove includes/dataitems/SMW_DI_String.php
- `SMWCsvResultPrinter` (includes/queryprinters/CsvResultPrinter.php)
- `SMWJsonResultPrinter` (includes/queryprinters/JsonResultPrinter.php)

## Hooks
- `SMWSQLStore3::deleteSubjectBefore` (includes/storage/SQLStore/SMW_SQLStore3_Writers.php)
- `SMWSQLStore3::deleteSubjectAfter` (includes/storage/SQLStore/SMW_SQLStore3_Writers.php)
- `smwShowFactbox` (src/Factbox/Factbox.php)
- `smwUpdatePropertySubjects` (src/MediaWiki/Jobs/UpdateDispatcherJob.php)

## Member methods and variables
- Remove deprecated methods in `SMWPropertyValue` (includes/datavalues/SMW_DV_Property.php)
- Remove `SMWRecordValue::getDVs()` (includes/datavalues/SMW_DV_Record.php)
- Remove `SMWTimeValue::getXMLSchemaDate()` (includes/datavalues/SMW_DV_Time.php)
- Remove deprecated methods in `SMWWikiPageValue` (includes/datavalues/SMW_DV_WikiPage.php)
- Remove `SMWDataValue::clearErrors()` (includes/datavalues/SMW_DataValue.php) - noted as a todo and seems unused by all subclasses
- Remove deprecated methods in `SMWQueryProcessor` (includes/query/SMW_QueryProcessor.php
- Remove deprecated methods in `SMW\RawResultPrinter` (includes/queryprinters/RawResultPrinter.php)
- Remove deprecated `SMWQueryResult::getQueryLink()` (includes/storage/SMW_QueryResult.php)
- Remove deprecated `$m_params` and methods in `SMW\ResultPrinter` (includes/queryprinters/ResultPrinter.php)
- Remove `ValueDescription::getDataValue()` (src/Query/Language/ValueDescription.php)

## Other
- Remove deprecated `SMW_HEADER_*` defines (includes/Defines.php) and deprecated support in `SMWOutput::requireHeadItem()` (includes/SMW_Outputs.php)
- Remove deprecated `TYPE_STRING` (includes/dataitems/SMW_DataItems.php) and `_str` entries in `SMW\DataTypeRegistry::initDatatypes()` (src/DataTypeRegistry.php)

**Comment by JeroenDeDauw** [comment]
Thanks all for compiling these lists. Really useful!

**Comment by JeroenDeDauw** [comment]
Is there anything that will be a breaking change to the normal end user not yet in the list? So far I have just these things for my SMWCon presentation: MW compat break, PHP compat break, type NS removal, SemanticStatistics removal, maintenance script alias removal.

**Comment by mwjames** [comment]
See #1371

**Comment by mwjames** [comment]
Some extensions rely on certain interfaces/static methods therefore only a major release can be used to break the interface (those that use Composer will unlikely break because dependencies need to be updated manually) 

- `SMWQueryProcessor` has some major flaws and requires re-factoring in a way it is a more self-explanatory and allows for some testing
- `SMWStore` I'm unhappy with the way the current abstract class is specified and used as interface
- `SMWExporter` something needs to be done to this class

A side from above issues: 

- #839 should be done
- #127 ???

**Comment by JeroenDeDauw** [comment]
PRs up for all the things that remained
