### ISSUE TITLE
2.3 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1061]
Tracking issue for the 2.3 release.

* [Release notes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/RELEASE-NOTES.md)
* [Open issues for 2.3](https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestones/SMW%202.3)
* [2.3 issues already closed](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues?q=milestone%3A%22SMW+2.3%22+is%3Aclosed)
* [Changes since 2.2](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.2.0...master)

--

RC1 target: October 7th

* [x] Finalize rel notes
* [x] Update version number
 * [x] SemanticMediaWiki.php
 * [x] COMPATIBILITY.md
* [x] Create tag
* [x] Create tarballs
* [x] Run composer update for SMW sandbox
* [x] Announce via mail
* [x] Do a release tweet on Twitter

--

Release target: October 18th
* [x] Blocker: remove DBAL dependency
* [x] Finalize rel notes (include contributors (`git shortlog -sn 2.2.0...2.3.0`))
* [x] Update version number
 * [x] SemanticMediaWiki.php
 * [x] README.md
 * [x] COMPATIBILITY.md
* [x] Check Special:Version
* [x] Create branch
* [x] Create tag
* [x] Create tarballs
* [x] Update release template
* [x] Run `composer update` for SMW wiki
* [x] Run `composer update` for SMW sandbox
* [x] Announce on wiki
* [x] Update version on wikidata, en, de, mw and wikiapiary
* [x] Touch LocalSettings.php
* [x] Announce via mail
* [x] Do a release tweet on Twitter

**Comment by JeroenDeDauw** [comment]
The milestone itself says July 21st. Who put this there? @kghbln @mwjames?

**Comment by kghbln** [comment]
Dunno, been there for quite some time. Sounds realistic to me, though.

**Comment by mwjames** [comment]
> The milestone itself says July 21st. Who put this there?

I just picked a date when I first created 2.3. Let's see how it goes.

**Comment by JeroenDeDauw** [comment]
It went by without any of us noticing apparently :) No point in doing a release yet if we don't have reason to though.

Fun fact: even though it's only been half the time since 2.2 as 2.2 was after 2.1 or 2.1 after 2.0, we already have more contributors now.

**Comment by mwjames** [comment]
> It went by without any of us noticing apparently :) No point in doing a release yet if we don't have reason to though.
 
I think no one will whine if it happens a month later.

**Comment by kghbln** [comment]
:+1: Gives me more time to document too. I know that this sounds like procrastination. ;)

**Comment by mwjames** [comment]
## Open issues

- [ ] Dbal isn't used therefore should be removed from the 2.3 release.

**Comment by JeroenDeDauw** [comment]
> Dbal isn't used therefore should be removed from the 2.3 release.

Again... >_> What idiot introduced this prematurely? Oh wait... me >_>

**Comment by mwjames** [comment]
MW 1.26 specific fixes include:

- API changes in 1.25 that caused tests to fail have been spaghetti adjusted with c2577df
- Flashy styles as encountered/described by https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1092#issuecomment-128219220 have been forced to load early with 9d0118e6

All test environments pass (has been a while) including 1.25/master-hhvm.

![image](https://cloud.githubusercontent.com/assets/1245473/9645393/99df75f8-51cb-11e5-863c-82390b77a166.png)

**Comment by JeroenDeDauw** [comment]
Fantastic!

@mwjames do you want to do the 2.3 rel soon? I'm thinking it'd be nice to do this before SMWCon, though that is still a bit under 2 months away anyway.

**Comment by mwjames** [comment]
Blazegraph (the TBD used by WDQ) has been added to official CI matrix (#1154 / [0]).

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/80583686

**Comment by mwjames** [comment]
>  do you want to do the 2.3 rel soon? I'm thinking it'd be nice to do this before SMWCon, though that is still a bit under 2 months away anyway.

@SemanticMediaWiki/testers @JeroenDeDauw @kghbln People should start testing like crazy to make it before the SMWCon.

**Comment by jaideraf** [comment]
I think we need a RC to ask more people to test.

**Comment by JeroenDeDauw** [comment]
@mwjames  It's still 5 weeks... Is more testing than usual needed? And is that a "yes" reply to my earlier question on starting with the 2.3 rel?

**Comment by JeroenDeDauw** [comment]
@mwjames if all is fine from your side I'll poke stuff to create an initial RC

**Comment by JeroenDeDauw** [comment]
IMO the release notes as they are need work to be user friendly. A lot of the things in there are too technical for most users to understand (and in some cases about details not relevant in the release notes).

**Comment by gesinn-it** [comment]
Is the release notes the only open issue that blocks the release? It would be great if 2.3 would be available soon. I had a look at the release notes, but I don't think I can help with "simplification".

**Comment by mwjames** [comment]
> A lot of the things in there are too technical for most users to understand (and in some cases about details not relevant in the release notes). 

Maybe but I'd like to keep them as it is makes it easier to revisit the list in case of a refresher instead of going through the git-log and I'm also not in favour to creating yet another CHANGELOG file.

Those marked as internal can be (and mostly are) skipped by users.

>  It would be great if 2.3 would be available soon.

We get there ...


>  I had a look at the release notes, but I don't think I can help with "simplification".

Well, you could:
- look at the release notes, "pick a number", and try to understand the idea behind it and give it a shot on either [0] or your local wiki.
- run `composer phpunit` from your local installation with master to see whether it returns with the same results as reported by [1, 2]
- you sent us some test cases we haven't considered yet [3, 4] / (you don't have to be core-developer to model test cases) to increase our overall confidence and help detect potential regressions now and in future

While independent of the 2.3 release, you could help @kghbln in his effort to update smw.org with the upcoming changes.

Tests (either manual or automatic) are our bread–and–butter to make changes being less disruptive to users and let us work more effectively in implementing new features but having an updated smw.org document base is equally important [5], so there are different ways you can contribute (let's called it):
- __C__ ode (that's obvious but comes in different tints and shades)
- __O__ organize (smw.org, sandbox, SMWCon, spread the word, update issues on github to be easily accessible in understanding what the "real" issue is, Version used + examples that can be copy-and-paste [6] without the need to spend hours in figuring it out yourself etc.)
- __D__ ocument, write examples, and translate
- __E__ valuate, assert, test (verifiable using a scripted approach, nothing is more frustrating then having users claim it doesn't work without a way to make it verifiable which of course takes effort but this is a shared burden)

[0] http://sandbox.semantic-mediawiki.org/wiki/Issue/1146
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1061#issuecomment-137251931
[2] #1142 / https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests#running-tests
[3] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests/phpunit/Integration/ByJsonScript/Fixtures
[4] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests#integration-tests
[5] http://wikimedia.7.x6.nabble.com/Imported-vocabularies-not-generating-RDF-as-expected-tp5053263p5053265.html
[6] https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/1#issuecomment-143467925

**Comment by JeroenDeDauw** [comment]
> Maybe but I'd like to keep them as it is makes it easier to revisit the list in case of a refresher instead of going through the git-log and I'm also not in favour of creating yet another CHANGELOG file.

> Those marked as internal can be (and mostly are) skipped by users.

I understand that it is nice to have a list of important technical changes for developers. Mixing those together with the functionality changes relevant to end users is not nice though, which is why we have the internal changes section. As they are now, the release notes have many technical things mixed in together with the features though. For instance, the SPARQLStore section has "Extended TurtleTriplesBuilder to split larger turtle sets into chunks". I'm imagining users starting to read this, their eyes glazing over, them closing the window and deciding they'll consider if they want to upgrade again when the next version is released.

**Comment by JeroenDeDauw** [comment]
I'll do the RC1 work later today (unless James screams murder at me), so we can have the thing done in 2 weeks.

**Comment by mwjames** [comment]
> I'll do the RC1 work later today (unless James screams murder at me)

:+1: I'm already on the pre-2.4 train, so doing a RC1 works for me.

**Comment by JeroenDeDauw** [comment]
Would be nice to have a [tarball downloading service](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1187) before we make the 2.3 release, and certainly before SMWCon.

**Comment by mwjames** [comment]
> I'll do the RC1 work later today (unless James screams murder at me)

I just run a cross-check and it turns out Semantic Maps uses `SMWDataValue::prepareValue( $value, $comparator );` which has been killed in https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/6ab4dfa154bc252799ca8f7fa9fe4d313b9517bf#diff-954737db17a53c17e68e7adc81da0d82

So I have re-added ... damn it

**Comment by mwjames** [comment]
> which has been killed in 6ab4dfa#diff-954737db17a53c17e68e7adc81da0d82

Re-added with 90862e9e1 but has been deprecated and is going to removed with 3.0.

**Comment by mwjames** [comment]
Tests have been run against SMW master for the following repositories:

![image](https://cloud.githubusercontent.com/assets/1245473/10268587/d1b30c78-6abd-11e5-98ea-ac0531b435ce.png)

PS: This process needs automation.

**Comment by JeroenDeDauw** [comment]
Thanks a lot for running those tests!

> PS: This process needs automation.

Yeah, that'd be great. Perhaps create a ticket for it?

**Comment by JeroenDeDauw** [comment]
I totally forgot about the RC1 >_>. Will get to that now.

**Comment by JeroenDeDauw** [comment]
I've updated the compat matrix to list 2.3 has beta support for PHP 7. @mwjames is that correct? We still don't have the tests pass right?

**Comment by kghbln** [comment]
I currently have no idea when to document all the great improvements on the wiki. Thus you can take your time.

**Comment by JeroenDeDauw** [comment]
@kghbln that is much in line with making the release notes more readable. The wiki basically will have a more verbose version (which in some cases we perhaps should link to from the rel notes).

**Comment by mwjames** [comment]
> . @mwjames is that correct? We still don't have the tests pass right?

The API tests don't pass in full but that is a MW 1.26 issue (well two issues are only appear in connection with PHP 7  but again API related as indicated by https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1142#issuecomment-143142046).

**Comment by JeroenDeDauw** [comment]
Does that mean you think we can list PHP 7 as a supported PHP version?

**Comment by mwjames** [comment]
> Does that mean you think we can list PHP 7 as a supported PHP version?

PHP 7 hasn't been released yet, so stating beta support isn't wrong and maybe @jongfeli can weigh in.

**Comment by JeroenDeDauw** [comment]
Yeah well sure it has not been released. However it's at RC4. So if SMW works with RC4, its also going to work with PHP 7 itself...

@mwjames can you clarify in the release notes what the "Experimental features" section is about?

**Comment by mwjames** [comment]
> can you clarify in the release notes what the "Experimental features" section is about?

Those are full functional but not enabled by default which means the user has to make a conscious choice (== s(he) has to read the release notes in order to be able to use/enable the feature).

Also, those "Experimental features" will spit out some extra log entries to monitor the feature and should be removed by the time it is no longer declared as experimental (which is planned to be 2.4 if nothing unforeseen happens).

**Comment by JeroenDeDauw** [comment]
> has to read the release notes

oh dear :D
Ok, thanks for explaining, I'll add a note.

**Comment by jongfeli** [comment]
As for PHP 7 and SMW. The Wiki on our test server (MW 1.26alpha, PHP 7 RC4 on Windows Server 2008) runs just as you would expect, but it is roughly 2.5 times faster compared to PHP 5.6. This server also generates an "offline version" of our wiki to use with **XAMPP**. It does this with MW and SMW maintenance scripts and this works just fine under PHP 7.

The problem, if there is one,  is not MW or SMW but extensions that have deprecated stuff in them related to PHP 7 or they simply "don't work" under MW 1.26. On our production server we are at MW 1.24.2 at the moment and when switching to PHP 7 we also want to move to the next "stable" version of MW, skipping 1.25. I noticed that the MW wiki is on 1.27 so I am not sure what is coming and when.

**Comment by JeroenDeDauw** [comment]
@jongfeli thanks for the info!

@mwjames think this better get merged before rel... #1214

**Comment by JeroenDeDauw** [comment]
@mwjames can you please add some explanatory line to the "Property/Subject deletion" section of the rel notes? I need some help there... not clear to me what the scope of the changes in this release is.

**Comment by mwjames** [comment]
>  I need some help there... not clear to me what the scope of the changes in this release is. Is this some kind of bugfix, 

The main point here is that once you delete a subject, property, or value it no longer appears in queries (it was possible in previous releases). #1100 / #1151 / [1] contains some test cases. #1216 belongs to the same category but it will be merged with 2.4. 

[1] http://wikimedia.7.x6.nabble.com/I-have-a-page-already-been-deleted-but-it-still-appears-when-querying-td5053443.html

**Comment by mwjames** [comment]
> @mwjames think this better get merged before rel... #1214

Done.

**Comment by mwjames** [comment]
> MW 1.24.2 at the moment and when switching to PHP 7 we also want to move to the next "stable" version of MW, skipping 1.25. I noticed that the MW wiki is on 1.27 so I am not sure what is coming and when.

@jongfeli I cannot recommend 1.26/1.27, see #1208 as to why.

**Comment by jongfeli** [comment]
Ok :thumbsup:, thanks for the ping.

**Comment by mwjames** [comment]
#1219 is blocker

**Comment by JeroenDeDauw** [comment]
> The main point here is that once you delete a subject, property, or value it no longer appears in queries (it was possible in previous releases). #1100 / #1151 / [1] contains some test cases. #1216 belongs to the same category but it will be merged with 2.4. 

Right. So this whole section is about a bugfix then, rather than a significant new feature? (I understand that fixing the bug might have been quite involved, though that really is not relevant for the users.)

**Comment by mwjames** [comment]
#1223 is a blocker

**Comment by mwjames** [comment]
#1222 is a blocker

**Comment by JeroenDeDauw** [comment]
> #1222 is a blocker

Well, if it was broken in 2.2 as well, then not really. Though we can of course wait if it will be fixed soon.

**Comment by mwjames** [comment]
> Well, if it was broken in 2.2 as well, then not really. Though we can of course wait if it will be fixed soon.

Fixed with ca32ff4.

**Comment by JeroenDeDauw** [comment]
I'm concluding the speed of James lies somewhere between the speed of sound and the speed of light.

![james-speed](https://cloud.githubusercontent.com/assets/146040/10621699/9f21f90a-7782-11e5-81c1-6689882196d0.gif)

**Comment by gesinn-it** [comment]
(rofl) +1

**Comment by JeroenDeDauw** [comment]
@mwjames what are in your opinion the most important (non-internal) changes in SMW 2.3 besides the SPARQLStore awesomeness? I'd like to do another pass on the rel notes before releasing.

**Comment by mwjames** [comment]
I'm not sure what do with #1228 since it is caused by a PHP bug.

**Comment by mwjames** [comment]
smw.org is also on PHP 5.3.3 which most likely will encounter the same issue as #1228 but as I said before I'm somewhat reluctant to change the signature just to accommodate a PHP bug.

**Comment by JeroenDeDauw** [comment]
> smw.org is also on PHP 5.3.3

![double_facepalm](https://cloud.githubusercontent.com/assets/146040/10662476/63df6056-78b5-11e5-8062-b5beafc4238d.png)

I created #1229

**Comment by JeroenDeDauw** [comment]
@mwjames what are in your opinion the most important (non-internal) changes in SMW 2.3 besides the SPARQLStore awesomeness? I'd like to do another pass on the rel notes before releasing.

**Comment by mwjames** [comment]
> what are in your opinion the most important (non-internal) changes in SMW 2.3 besides the SPARQLStore awesomeness? 

I went through the list and maybe the query/parser cache stuff but that's an experimental feature so it doesn't really count otherwise it contains a lot of piecemeal caused by trying to fix one thing and ending up fixing two other things.

**Comment by JeroenDeDauw** [comment]
Ok thanks. I'll try to do the release stuff soon. Leaving for some conference now, so not sure if I'll manage today

**Comment by mwjames** [comment]
> so not sure if I'll manage today

... it can also happen tomorrow or the day after, no rush ...

**Comment by JeroenDeDauw** [comment]
If we want to release before SMWCon, then let's try not delay any further. Of course, we could also release it during SMWCon for increased theatrics :)

**Comment by thingles** [comment]
FWIW, I just [upgraded WikiApiary to 2.3 RC1](https://wikiapiary.com/wiki/Special:Version) (766fdff) (from 2.3 alpha 1)

**Comment by JeroenDeDauw** [comment]
@mwjames please fix #1230

**Comment by JeroenDeDauw** [comment]
Tag and branch created. Tarballs uploaded. SMW wiki software updated. Still need to announce.

**Comment by JeroenDeDauw** [comment]
@kghbln can you do the wiki announce?

**Comment by kghbln** [comment]
@JeroenDeDauw This has finally been done. Now only the mail announcement is left to you.

**Comment by kghbln** [comment]
@JeroenDeDauw Thanks a bunch!
