### ISSUE TITLE
2.3.1 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1322]
* [x] Update release notes
* [x] Update version number
 * [x] SemanticMediaWiki.php
* [x] Create tag
* [x] Create tarballs
* [ ] ~~Run composer update for SMW~~
* [x] Announce via mail
* [x] Do release tweet on Twitter

## Preliminary notes

```
Commits on Nov 02, 2015
 ...	Do not replace `_` in ImportValueParser	 93699a1
Commits on Nov 07, 2015
 ...	Add InTextAnnotationParserStrictMode flag, refs #1252 …	 dd6cbbd
 ...	EmbeddedQueryDependencyLinksStore to create object ID if not availabl… …	 68b7ec5
 ...	EmbeddedQueryDependencyLinksStore limit ID creation to specific NS, r… …	 5b95edc
Commits on Nov 12, 2015
 ...	Attempt to fix 1.26/1.27 API/RawMode output change, refs #1268 …	 311961c
 ...	Support importing recursive annotation per query, refs 1255, 1068 …	 ec9d82d
Commits on Dec 17, 2015
 ...	Setting to force HttpVersion for RepositoryConnector, refs 1306

```

**Comment by nemobis** [comment]
> Update release notes

Please mention that, as Nikerabbit found out, https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/bce5b6c601651ec283e10e96998a375b77b557b4 fixes https://phabricator.wikimedia.org/T121761#1887668

**Comment by JeroenDeDauw** [comment]
James, are you expecting help with this? I'm happy to do some of that, though doing the release notes is really something no one but you can do well for things you changed.

**Comment by mwjames** [comment]
> doing the release notes is really something no one but you can do well for things you changed.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-2.3.1.md

**Comment by JeroenDeDauw** [comment]
> James, are you expecting help with this?

I'm happy to do some of the stuff here, not clear to me what the status is though

**Comment by mwjames** [comment]
>  not clear to me what the status is though

Well, users can test 2.3.1 branch (if they want to or it can just be released) but my focus is on 2.4.

**Comment by JeroenDeDauw** [comment]
Ok, I'll up the version number and do the other release stuff then

**Comment by JeroenDeDauw** [comment]
Did not get to it today, will do tomorrow

**Comment by JeroenDeDauw** [comment]
Doing this now. Waiting for build to finish... https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/builds/100091208
