### ISSUE TITLE
years appearing as "1 January 1970 + timestamp"

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1348]
This is an old one, first reported in 2011 I think: years before 1100(?) appearing as "1 January 1970 + timestamp", as demonstrated here: http://sandbox.semantic-mediawiki.org/wiki/User:Cavila/test   

See https://phabricator.wikimedia.org/T56151, which was closed as being a duplicate of another report, which for some reason I cannot find.

**Comment by mwjames** [comment]
>  which was closed as being a duplicate of another report, which for some reason I cannot find.

https://phabricator.wikimedia.org/T49259

## Solution

After a "very" quick look, the following change to `SMWTimeValue` should allow for a correct interpretation of a year annotation.

```php
-		// Check if it's parseable by wfTimestamp when it's not a year (which is wrongly interpreted).
-		if ( strlen( $value ) != 4 && wfTimestamp( TS_MW, $value ) !== false ) {
+		// If no space is present in the user value we assume it is a year
+		// value without any further information
+		if ( strpos( $value, ' ' ) === false ) {
+			$this->m_dataitem = new SMWDITime( $this->getCalendarModel( null, $value, null, null ), $value );
+		} elseif ( strlen( $value ) != 4 && wfTimestamp( TS_MW, $value ) !== false ) {
+			// Check if it's parseable by wfTimestamp when it's not a year (which is wrongly interpreted).
```
```
[[Date::-1000]], [[Date::-100000]]

[[Date::910]], [[Date::910 AD]], [[Date::910 BC]]

[[Date::1582]], [[Date::1582 AD]], [[Date::1582 BC]]

[[Date::1910]], [[Date::1910 AD]], [[Date::1910 BC]]

[[Date::11910 ]], [[Date::11910 AD]], [[Date::11910 BC]]
```

## Tasks

- [ ] Do some more manual testing (in case I missed something)
- [ ] Turn this into a PR
- [ ] Write some tests (for this class I can live without an specific unit test BUT I'd like to see some [0] integration tests so that user input/output is covered in case the class gets an overhaul in future)

[0] https://www.semantic-mediawiki.org/wiki/Help:Integration_tests

**Comment by mwjames** [comment]
On a side note with [0] noting that:

> I tried "910 AD" as a workaround, and this sets the property value correctly, but it is displayed without the "AD" -- "910 AD" becomes "910" (in contrast, "910 BC" becomes "910 BC"). This is a problem because I sometimes want set other properties based on a query of existing values. Taking a date, displaying it, and the re-parsing it should not change the meaning of the date.

It is true that  "re-parsing it should not change the meaning of the date." but all non BC dates are assumed to be AD therefore the suffix AD is omitted whether it was explicitly mentioned or not.

Currently it is not possible (from the DB perspective) to distinguish between annotations that contained an explicit AD and those that did not (the storage only knows `1/-100000` as BC vs `1/11910` AD without storing information about whether AD was mentioned or not) .

For https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1348#issuecomment-169020611 examples the DB perspective looks like:

![image](https://cloud.githubusercontent.com/assets/1245473/12118118/0fcccd0a-b3c5-11e5-9e74-58b75200b300.png)

[0] https://phabricator.wikimedia.org/T49259

**Comment by Contrafibularity** [comment]
After the sandbox site was updated to the latest build of SMW, the example at http://sandbox.semantic-mediawiki.org/wiki/User:Cavila/test still showed "1 January 1970 ...". As you'd probably expect, the page just needed to be refreshed, so I resaved the page and the query is now showing "900 JL".
