### ISSUE TITLE
2.4.1 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1716]
2.4.1 target: 2016-07-12

* [x] Finalize rel notes
* [x] Update version number (2.4.1)
 * [x] SemanticMediaWiki.php
* [x] Create tag
* [x] Create tarballs
* [ ] Run composer update on `smw.org`
* ~~[ ] Announce via mail~~
* ~~[ ] Do a release tweet on Twitter~~

## Expected backports 

- [x] #1714
- [x] #1715 
- [x] #1717
- [x] #1725
- [x] #1726
- [x] #1729
- [x] #1730 
- [x] #1731 

(Unchecked items have not yet been backported)

- refs #1364
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/2.4.x

**Comment by JeroenDeDauw** [comment]
Does this fix something significant? As in, worth enough waiting with the 2.4 announcement?

**Comment by JeroenDeDauw** [comment]
Also easy to backport: #1717

**Comment by mwjames** [comment]
>  If the tag has already been created then, everyone will end up getting 2.4.1.

No 2.4.1 tag has been created so far.

> Does this fix something significant? As in, worth enough waiting with the 2.4 announcement?

Its significant as bug fix but I was thinking to have this done (as in creating the tag) in one or two weeks time (after some dust has settled).

@kghbln Should confirm that #1713 (aka #1714) is working now.

**Comment by JeroenDeDauw** [comment]
So you think we should just announce 2.4 now and not create the tag 2.4.1 with the already backported fixes before?

**Comment by JeroenDeDauw** [comment]
Ping @mwjames. I want to do the 2.4.0 rel ASAP so that is done, and am thus blocked on your input.

**Comment by mwjames** [comment]
> I want to do the 2.4.0 rel ASAP so that is done, and am thus blocked on your input.

Well, if you think instead of 2.4.0 announcing 2.4.1 is a good tactical manoeuvre (it would imply that we haven't tested enough that so soon after the release it already has a bunch of fixes) .

Anyway, I made the backports (and I expect to see a 2.4.2 within the next month), tests passed, and  https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.4.x/docs/releasenotes/RELEASE-NOTES-2.4.1.md is available as well, so feel free to make the 2.4.1 tag.

**Comment by mwjames** [comment]
@kghbln Any preference?

**Comment by kghbln** [comment]
> Any preference?

I think we should announce 2.4 and tag 2.4.1 so people are getting the latest version. Most end users will not recognise the difference between 2.4 and 2.4.0. So targeting 2016-07-12.

**Comment by kghbln** [comment]
> @kghbln Should confirm that #1713 (aka #1714) is working now.

This is cool now. Great! The script is currently running. Will report back as soon as it finished.

**Comment by JeroenDeDauw** [comment]
Sorry for not explaining my intent properly. My idea is to announce SMW 2.4 as usual in either case. The difference just being that in one case the download links will point to 2.4.0, and the other, they will point to 2.4.1. Like this we don't distract users from technicalities which they likely don't care about. It's also the option that is best for the users, so if anyone feels we're not going a good enough job because we made a minor release for their benefit, they can go **** themselves.

Anyway, great there already is a release notes. I will create the tag and do the 2.4.0 announce today.

**Comment by kghbln** [comment]
> The difference just being that in one case the download links will point to 2.4.0, and the other, they will point to 2.4.1.

No prob to point the download link on 2.4.0 to 2.4.1

**Comment by kghbln** [comment]
(27620/41159)   Finished processing ID 41203 (Semantic_MediaWiki_2.2.3_released#0#_QUERY74409240b8a2a35e9e5f3bb6c7eaf8a5)

27622 IDs refreshed.

Memory used: 459440552 (b: 23068664, a: 482509216) with a runtime of 3836.24 sec (63.94 min)

That's with xdebug on board. So things are fluffy now.

**Comment by kghbln** [comment]
> So things are fluffy now.

Actually not since I had to manually cancel the script after I got this report.
