### ISSUE TITLE
2.5.0 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1752]
Tracking issue for the 2.5 release.

- [Release notes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/RELEASE-NOTES.md)
- [Open issues for 2.5](https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestones/SMW%202.5.0)
- [2.5 issues already closed](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues?q=milestone%3A%22SMW+2.5.0%22+is%3Aclosed)
- [Changes since 2.4](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.4.0...master)

## rc.1 target: 2017-03-07

- [x] Shape rel notes
  - [x] Add missing commints tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
- [x] Update version number
  - [x] load.php
  - [x] COMPATIBILITY.md
- [x] Create tag
- [x] Create tarballs
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration 
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Ping testers group
- [x] Announce via mail
- [x] Do a release tweet on Twitter

## Release target: 2017-03-13

- [x] Finalize rel notes (include contributors (`git shortlog -sn 2.4.0...2.5.0`))
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
  - [x] Check [open issues](https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestones/SMW%202.5.0)
- [ ] At least document the version highlights on wiki
  - [x] Full-text search
  - [x] Provenance data recording
  - [ ] Property chain and language filter support in print request
  - [x] Edit protection
  - [x] Preferred property label support
  - [x] Query result cache
  - [x] Links in values
  - [x] Fixed properties
  - [ ] Special page "SemanticMediaWiki"
- [x] Update version number (2.5.0)
  - [x] load.php
  - [x] README.md in `/`
  - [x] README.md in `/docs/`
  - [x] COMPATIBILITY.md (release date etc.)
  - [x] INSTALL.md
- [x] Create branch
- [x] Create tag
- [x] Manage tarballs
  - [x] Create tarball
  - [x] Check tarball
  - [x] Download tarball to release page
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update` 
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration 
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
  - [x] Update [release template](https://www.semantic-mediawiki.org/wiki/Template:SMW_release_main_page)
- [x] Announce on wiki
- [x] Update version on wikidata, en, de, mw, wikiapiary and Free Software Directory
- [x] Announce via mail
- [x] Do a release tweet on Twitter
- [x] Update "README.md" and "INSTALL.md" in master according to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2333
- [x] Bump version in master to x.x.x-alpha - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2340

**Comment by mwjames** [comment]
## Tasks

- [ ] Remove `SMWSQLHelpers` before the release after it is clear that #1750 doesn't introduce any regression

**Comment by mwjames** [comment]
Maybe its time to start making preparations since we are ~540 commits into 2.5.0-alpha (2.4.0 was released on Jul 9) and avoid some frustration and time constraints as I recall from the last release process.

I don't have anything big left on my task list with the following features being available:

- Experimental query cache (and stats collection)
- Full-text support for MySQL/SQLite
- Preferred property label/Property description, dynamic select of a lang version in a query using `+lang=...`
- `@@@` annotation syntax support
- Reference and external identifier support
- Support property.chain notation in printrequests

I'm not yet ready to call for a code-freeze but I'd like some people to use the 2.5.0-alpha version (its pretty stable otherwise our tests would tell us something else and the sandbox seems fairly stable as well) to get some early feedback as a lot of extra refactoring was necessary to support those listed features.

Tests went from 2.4 ~85% coverage (Tests: 3685, Assertions: 12014) to preliminary Tests: 4300, Assertions: 13891 (~87% coverage)

**Comment by JeroenDeDauw** [comment]
I still think it'd be nice to just create a [release whenever a new feature is available](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1685). Put it in the release notes, create a tag, done. No need for code freeze or a long process of trying to figure what happened half a year ago. It is what I do with Maps, and it is a lot more fun for sure.

**Comment by kghbln** [comment]
This builds up pressure on me to do at least a minimal documentation. I will try to do my very best.

**Comment by JeroenDeDauw** [comment]
The dates where are wrong now: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

**Comment by mwjames** [comment]
> Tests went from 2.4 ~85% coverage (Tests: 3685, Assertions: 12014) to preliminary Tests: 4300, Assertions: 13891 (~87% coverage)

I'm officially done with 2.5, now that master contains +850 commits for the 2.5 release cycle (compared to 2.4.x) and amounts a total of 4652 tests (Assertions: 14830) it is time to close the release.

**Comment by JeroenDeDauw** [comment]
Updated the initial comment with the list-o-doom

**Comment by kghbln** [comment]
@mwjames @JeroenDeDauw What about doing -rc0 today pinging testers and release next week according to the schedule?

**Comment by JeroenDeDauw** [comment]
rc0? One starts with rc1 AFAIK

Fine from my side

**Comment by JeroenDeDauw** [comment]
Thank you @mwjames for making the release notes so fluff right off the bat!

![130418ded199cdc061e2ce711c9092fd](https://cloud.githubusercontent.com/assets/146040/23639712/76ad175e-02e9-11e7-80f0-fd86d982754a.jpg)

**Comment by kghbln** [comment]
> rc0? One starts with rc1 AFAIK

Yeah, it is rc.1 according to [spec-item-9ff](http://semver.org/#spec-item-9). I got off track since MW uses rc.0 O_o

**Comment by kghbln** [comment]
@SemanticMediaWiki/testers It will be nice if you could test and provide feedback. Thanks a lot.

**Comment by JeroenDeDauw** [comment]
> Yeah, it is rc.1 according to spec-item-9ff.

Bleh, that's not what we've been using... does not really matter I suppose

**Comment by kghbln** [comment]
> Bleh, that's not what we've been using... does not really matter I suppose

Oh, I guess semver is more complicated that one may expect. No, does not really matter as long as we get the regular releases right. I myself was more unhappy that the mailinglist munched all linebreaks. I was in grump as I saw this.

**Comment by kghbln** [comment]
@mwjames Note that sandbox still runs master thus updating beyond rc.1

**Comment by kghbln** [comment]
@mwjames @JeroenDeDauw I will add some more docu to the wiki today. Since we got translation updates today we could release tomorrow. Any objections?

**Comment by JeroenDeDauw** [comment]
![hyperspacecat](https://cloud.githubusercontent.com/assets/146040/23849628/94b51c18-07dc-11e7-9cb2-1fe7b6e7d23f.jpg)

Wow things are moving soooooo faaaaaaaaaaaaaaaaaaaaaaast

All OK from my side. Want me to do anything?

**Comment by kghbln** [comment]
> Want me to do anything?

You could somehow retrieve the contributors. If you want https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2318 in you could act on this one, too. + merging your pull request of today. I guess the rest may be up to me.

**Comment by JeroenDeDauw** [comment]
I'll have a look at the stuff tomorrow

**Comment by JeroenDeDauw** [comment]
The array syntax stuff provides no benefit to the user. Since there is some chance it breaks something, I'd be included to merge this AFTER the release. I suppose that does make backporting harder, so it is a bit of a tradeoff.

**Comment by JeroenDeDauw** [comment]
`git shortlog -sn 2.4.0...master`

>   688  mwjames
    54  Karsten Hoffmeyer
    38  Jeroen De Dauw
    37  Niklas Laxström
    14  translatewiki.net
    13  jeroendedauw
     5  Kghbln
     5  Maciej Brencz
     4  Siebrand Mazeland
     3  jongfeli
     2  Alex Winkler
     2  Toni Hermoso Pulido
     1  Amire80
     1  Felipe de Jong
     1  Jaider Andrade Ferreira
     1  James Forrester
     1  Justin Du
     1  Seb35
     1  Sophivorus
     1  Stephan Gambke
     1  Virginia Cepeda
     1  s7eph4n

**Comment by kghbln** [comment]
Ok, let's get 2.5.0 out to the world.

**Comment by kghbln** [comment]
Given that we are now a fortnight into having 2.5.0 out and seeing the issue reports we hardly had any issues so far. This is a leap forward in comparison with previous releases. So thank you @mwjames for such robust programming flanked by automated testing.
