### ISSUE TITLE
2.4.3 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2025]
Tracking issue for a possible (not yet defined) release.
- [x] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1751#issuecomment-261686523 done with https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/fd6b4cf98071a1713560c1d95687cff9ab6a407f
- [x] #1975 done with https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/a022f86b85b259c50f10629974f5e5fbb678974b

**Comment by JeroenDeDauw** [comment]
We can just create a tag on the branch after bumping the number that shows on Special:Version to fix the PHP compat issue. For such fixes doing the whole release stuff is such process overhead...

**Comment by kghbln** [comment]
> For such fixes doing the whole release stuff is such process overhead...

I agree if it was just for 1751 but there is also 1975 in the pipeline waiting for feedback and action.

**Comment by kghbln** [comment]
@JeroenDeDauw @mwjames In case https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/789b6a8178c22261bd8e6b5857995af22e12b0e9 is fluffy we could do on Monday

- [ ] Finalize rel notes
- [ ] Update version number (2.4.3)
  - [ ] SemanticMediaWiki.php
- [ ] Create tag
- [ ] Create tarballs
- [ ] Run composer update on `smw.org`
- [ ] Announce via mail
- [ ] Do a release tweet on Twitter

**Comment by JeroenDeDauw** [comment]
Sounds good. Beware that I'm currently doing two jobs, so I don't have a lot of time to spare

**Comment by kghbln** [comment]
> Sounds good. Beware that I'm currently doing two jobs, so I don't have a lot of time to spare

No worries. See #2060
