### ISSUE TITLE
2.4.4 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2088]
- [x] Finalize rel notes - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2103
- [x] Update version number (2.4.4) - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2103
  - [x] load.php
- [x] Create tag
- [x] Create tarballs
- [x] Run composer update on `smw.org`
- [x] Document release on `smw.org`
- [x] Announce via mail
- [x] Do a release tweet on Twitter

**Comment by kghbln** [comment]
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2016 @JeroenDeDauw If we cannot fix soon and easily I could add platform manually to composer.json prior to generating the tarballs. Should work I guess.
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2078
