### ISSUE TITLE
2.4.6 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2261]
## Release work
- [x] Finalize rel notes
- [x] Update version number (2.4.5)
  - [x] load.php
- [x] Create tag
- [x] Create tarballs
- [x] Run composer update on `smw.org`
- [x] Document release on `smw.org`
- [x] Announce via mail
- [x] Do a release tweet on Twitter
