### ISSUE TITLE
2.5.1 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2350]
Date: 2017-04-19

[2.5.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
- [x] Copy release notes to `/docs/releasenotes/`
- [x] Update README.md in `/docs/`
- [x] Update version number
  - [x] load.php
- [x] Create tag
- [x] Create tarballs
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Copy release notes to `/docs/releasenotes/` in "master"
- [x] Announce on wiki
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce via mail
- [x] Do a release tweet on Twitter

**Comment by mwjames** [comment]
This release will contain some fixes and changes otherwise it will take too long before they become available and are released with 3.0.

**Comment by kghbln** [comment]
Any objections on me doing this next Wednesday. I do not see any bugs rolling in which should somehow be fixed and moved in here so ...

**Comment by mwjames** [comment]
> Any objections on me doing this next Wednesday?

I'll try to squeeze in the changes I'd like to see being addressed by the end of tomorrow, so that Wednesday should be fine.

**Comment by kghbln** [comment]
> I'll try to squeeze in the changes I'd like to see being addressed by the end of tomorrow, so that Wednesday should be fine.

In case you need more time just drop a note here. Also possible to do it a week later.

**Comment by kghbln** [comment]
This is still work in progress. Awful time management today from my side. Will do the open steps later.

**Comment by JeroenDeDauw** [comment]
I did the release tweet. Such much retweet? :) https://twitter.com/SemanticMW

**Comment by kghbln** [comment]
> I did the release tweet. Such much retweet?

I guess the retweets happen after sending out the release mail which I have just done.
