### ISSUE TITLE
2.5.2 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2433]
Date: TBD

* [2.5.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.x)
* [2.5.1... 2.5.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.1...2.5.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
- [x] Copy release notes to `/docs/releasenotes/`
- [x] Update README.md in `/docs/`
- [x] Update version number
  - [x] load.php
- [x] Create tag
- [x] Create tarballs
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Add release docu to "master"
  - [x] Copy release notes to `/docs/releasenotes/`
  - [x] Update README.md in `/docs/`
- [x] Announce on wiki
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce via mail
- [x] Do a release tweet on Twitter

**Comment by kghbln** [comment]
@mwjames @JeroenDeDauw Will do the release next week, most likely on Tuesday. @mwjames Thanks for awesomeness!

**Comment by kghbln** [comment]
Issues prevent me from doing it today. Scheduled for tomorrow now.

**Comment by jamesmontalvo3** [comment]
:( Anything I can help with?

**Comment by JeroenDeDauw** [comment]
The normal procedure is posting images of fluffy bunnies. Let me demonstrate

![fluffz](https://cloud.githubusercontent.com/assets/146040/26123576/adec77d6-3a7b-11e7-8fe9-6119ffa4483a.jpg)

yw!

**Comment by jamesmontalvo3** [comment]
The real talent appears to lie in the ambiguity of the fluffy creature...are we sure it's a bunny? Or a cat? Or something else we don't even know about?

**Comment by kghbln** [comment]
> The normal procedure is posting images of fluffy bunnies.

This almost triggered immediate action. :)

> are we sure it's a bunny? Or a cat? Or something else we don't even know about?

Well, I'd like to know if what we see - this is probably an encounter of the third kind - is defying gravity. Can you tell from experience?

**Comment by jamesmontalvo3** [comment]
@kghbln @mwjames @JeroenDeDauw Thanks for this, and all, releases!

@kghbln I'd say the way all the fur is pointing upwards it seems that it's not a zero-gravity, but something is forcing the upward motion. Perhaps some turbofan system on the bunny's undercarriage? Like hovercat?

**Comment by kghbln** [comment]
> Perhaps some turbofan system on the bunny's undercarriage? Like hovercat?

Well in that case I guess it must be caused by the ["Monroe effect"!](https://upload.wikimedia.org/wikipedia/commons/8/8d/Marilyn_Monroe_photo_pose_Seven_Year_Itch.jpg) :)
