### ISSUE TITLE
2.5.3 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2467]
Date: TBD

* [2.5.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.x)
* [2.5.2... 2.5.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.2...2.5.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
- [x] Copy release notes to `/docs/releasenotes/`
- [x] Update README.md in `/docs/`
- [x] Update version number
  - [x] load.php
- [x] Create tag
- [x] Create tarballs
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Add release docu to "master"
  - [x] Copy release notes to `/docs/releasenotes/`
  - [x] Update README.md in `/docs/`
- [x] Announce on wiki
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce via mail
- [x] Do a release tweet on Twitter

**Comment by kghbln** [comment]
@mwjames I re-scheduled this to June 28. Thus we have this ans SRF 2.5.1 on the same day.

**Comment by kghbln** [comment]
@mwjames What about doing this during the upcoming week?

**Comment by cicalese** [comment]
I am eagerly awaiting this release. Thanks!

**Comment by kghbln** [comment]
NASA had an issue that still needed be sorted out. It appears that the respective issue may be dealt with this weekend so from my personal perspective it should not take too long form now.

**Comment by cicalese** [comment]
Great! Thanks!

**Comment by kghbln** [comment]
> NASA had an issue that still needed be sorted out. It appears that the respective issue may be dealt with this weekend so from my personal perspective it should not take too long form now.

@mwjames I guess we are ready to move on with this one ...?

**Comment by mwjames** [comment]
>  I guess we are ready to move on with this one ...?

:+1:

**Comment by kghbln** [comment]
Cool, I will be having tea soon but thereafter I am going to proceed with it.

**Comment by kghbln** [comment]
Done!
