### ISSUE TITLE
2.5.4 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2539]
Date: 2017-08-07

* [2.5.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.x)
* [2.5.3... 2.5.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.3...2.5.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
- [x] Copy release notes to `/docs/releasenotes/`
- [x] Update README.md in `/docs/`
- [x] Update version number
  - [x] load.php
- [x] Create tag
- [x] Create tarballs
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Add release docu to "master"
  - [x] Copy release notes to `/docs/releasenotes/`
  - [x] Update README.md in `/docs/releasenotes/`
- [x] Announce on wiki 
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce via mail (@JeroenDeDauw suggests to use series instead of branch. :)
- [x] Do a release tweet on Twitter

**Comment by kghbln** [comment]
@bawolff, @mwjames and @JeroenDeDauw Now rescheduled to Monday, August 7, 2017. I will ping as soon as this is done so the phab task  T109652 may  be published.

**Comment by kghbln** [comment]
@bawolff FYI: SMW 2.5.4 was now released and announced.
