### ISSUE TITLE
Modernize maintenance scripts

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#257]
'''Contact person:''' [[Jeroen De Dauw]]

The maintenace scripts still use the old system, and should be migrated to use a class extending Maintenance, as is already done for the setup maintenance script. '''[independent]'''
### Status
- [x] `rebuildData.php` `SMW\Store\Maintenance\DataRebuilder` #244
- [x] `rebuildConceptCache.php` `SMW\Store\Maintenance\ConceptCacheRebuilder` #187
- [x] `rebuildPropertyStatistics.php` PropertyStatisticsRebuilder, #269, #267
- [x] setup maintenance script is missing unit tests
- [x] SMW_dumpRDF.php
