### ISSUE TITLE
2.5.5 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2604]
Date: 2017-10-18

* [2.5.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.x)
* [2.5.4... 2.5.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.4...2.5.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
- [x] Copy release notes to `/docs/releasenotes/`
- [x] Update README.md in `/docs/`
- [x] Update version number
  - [x] load.php
- [x] Create tag
- [x] Create tarballs
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Indicate alpha version of presumably upcoming release on 2.5.x branch
- [x] Add release docu to "master"
  - [x] Copy release notes to `/docs/releasenotes/`
  - [x] Update README.md in `/docs/releasenotes/`
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [ ] Announce on wiki 
- [x] Announce via mail (@JeroenDeDauw suggests to use series instead of branch. :)
- [x] Do a release tweet on Twitter
- [ ] In case no 2.5.6 release is done revert back the version info on the 2.5.x branch

**Comment by kghbln** [comment]
No more translations backports to 2.5.x. Something got messed up right after the 2.5.4 release since every language file now has merge conflicts. Tought luck.

**Comment by kghbln** [comment]
I have rescheduled this to 2017-10-18

**Comment by kghbln** [comment]
@mwjames What about this one? Some more goodies to backport or should I perhaps reschedule again by a month?

**Comment by mwjames** [comment]
> what about this one? Some more goodies to backport or should I perhaps reschedule again by a month?

If you think you have time, I'd say fire away.

**Comment by kghbln** [comment]
@mwjames @JeroenDeDauw That's done basically. Will do the announcements later.
