### ISSUE TITLE
Remove res/images folder

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2736]
## Target release

3.0

## Issue

I'd like to see that the `res/images` folder is removed. It contains images that should be embedded as base64 in the relevant css file.

`ResourceLoader` has good support for embedded base64 images hence making this folder go away is a step to more cleanliness and avoids issue with setting relative paths.

## Tasks

- [x] Find out which images are still used and where
  - [x] browse_icon.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2869
  - [x] browse_iconsmall.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2869
  - [x] info.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2691
  - [x] note.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2691
  - [x] rdf_flyer.10.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2869
  - [x] rdf_flyer.12.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2869
  - [x] rdf_flyer.18.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2869
  - [x] search_icon.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2869
  - [x] searchgray_iconsmall.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2869, https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2886 
  - [x] smw_button.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2885
  - [x] sort_down.gif - unused - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2900
  - [x] sort_none.gif - unused - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2900
  - [x] sort_up.gif - unused - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2900
  - [x] warning.png - https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2691
  - [x] world.png - unused -> https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2872
- [x] Convert them (see [0]) and add them to the related CSS rule

[0] https://www.base64-image.de/

**Comment by kghbln** [comment]
@mwjames This appears to be an easy task, so I will be taking this on.

**Comment by kghbln** [comment]
Even moar info: https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/332#issuecomment-338503345

**Comment by kghbln** [comment]
TODO https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2869#pullrequestreview-82348407
