### ISSUE TITLE
 [Task 3.0] Refactor SMWQueryProcessor

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2737]
## Target release

3.0

## Issue

refs https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2735#issuecomment-333927147, #2727 

Looking at the `SMWQueryProcessor` and the only valid classification one comes to mind (at least to me), this class is a MESS! 

The parameter handling is cluttered and less conceivable with various methods interacting on them in one form or the other.

## Tasks

Currently there is no clear design guideline on how this class should be refactored but preliminary task include:

- [ ] Collect a list of methods that are called from consumers to grasp an idea about the required interface methods
- [ ] `SMWQueryProcessor` is moved to `SMW\Query\Processor\LegacyProcessor` and aliased to `SMWQueryProcessor` so that the interface doesn't break for existing callers
- [ ] Create a `SMW\Query\Processor` class (you have a better name, go ahead!) that comes with a `Processor::getInstance` to avoid creating instances on each request (which could be 30+ on a single page request), the singleton pattern is allowed here as top factory

[0] https://www.base64-image.de/

**Comment by mwjames** [comment]
>  Collect a list of methods that are called from consumers to grasp an idea about the required interface methods


- SMWQueryProcessor::getValidatorForParams
  - not called outside of `SMWQueryProcessor`

- SMWQueryProcessor::getProcessedParams called by
  - SemanticResultFormats – TreeTest.php
  - SemanticResultFormats – SRF_SlideShowApi.php
  - SemanticMediaWiki – Query.php
  - SemanticScribunto – LibraryFactory.php
  - SemanticCompoundQueries – CompoundQueryProcessor.php
  - SemanticMediaWiki – TemplateRendererFactory.php
  - SemanticMediaWiki – QueryBuilder.php
  - SemanticComments – CE_CommentParserFunctions.php
  - SemanticMediaWiki – SpecialAsk.php

- SMWQueryProcessor::createQuery
  - SemanticMediaWiki – Query.php
  - SemanticScribunto – LibraryFactory.php
  - SemanticMediaWiki – TemplateRendererFactory.php
  - SemanticMediaWiki – DistinctEntityDataRebuilder.php
  - SemanticMediaWiki – QueryBuilder.php
  - SemanticCompoundQueries – CompoundQueryProcessor.php
  - SemanticMediaWiki – SpecialAsk.php
  - SemanticComments – CE_CommentParserFunctions.php

- SMWQueryProcessor::processFunctionParams  -> Use getComponentsFromFunctionParams which has a cleaner interface.
  - SemanticComments – CE_CommentParserFunctions.php
  - SemanticCompoundQueries – CompoundQueryProcessor.php

- SMWQueryProcessor::getComponentsFromFunctionParams
  - SemanticScribunto – LibraryFactory.php
  - SemanticMediaWiki – Ask.php
  - SemanticMediaWiki – ParametersProcessor.php
  - SemanticMediaWiki – SMW_QueryProcessor.php

- SMWQueryProcessor::getQueryAndParamsFromFunctionParams
  - SemanticMediaWiki – ProfileAnnotatorWithQueryProcessorIntegrationTest.php
  - SemanticMediaWiki – ConceptParserFunction.php
  - SemanticMediaWiki – QuerySourceIntegrationTest.php
  - SemanticMediaWiki – QueryResultQueryProcessorIntegrationTest.php
  - SemanticComments – CE_Comment.php
  - SemanticMediaWiki – SMW_QueryProcessor.php
  - SemanticMediaWiki – AskParserFunction.php

 - SMWQueryProcessor:: getResultFromFunctionParams -> vanish after release of SMW 1.8., -> Use getQueryAndParamsFromFunctionParams
   - SemanticFormsSelect – ApiRequestProcessor.php
   - SemanticFormsSelect – SemanticFormsSelect.php

- SMWQueryProcessor:: getResultFromQueryString -> vanish after release of SMW 1.8, use ->createQuery and -> getResultFromQuery
   - SemanticResultFormats – SRF_SlideShowApi.php
   - SemanticComments – CE_CommentParserFunctions.php

- SMWQueryProcessor:: getResultFromQuery
  - SemanticMediaWiki – QuerySourceIntegrationTest.php
  - SemanticComments – CE_Comment.php
  - SemanticMediaWiki – SMW_QueryProcessor.php
  - SemanticComments – CE_CommentParserFunctions.php
  - SemanticMediaWiki – AskParserFunction.php

- SMWQueryProcessor::getResultPrinter
  - SemanticMediaWiki – FormatListWidget.php
  - SemanticMediaWiki – DocumentationParserFunction.php
  - SemanticMediaWiki – SMW_ParamFormat.php
  - SemanticMediaWiki – SMW_QueryProcessor.php
  - SemanticCompoundQueries – CompoundQueryProcessor.php
  - SemanticMediaWiki – SpecialAsk.php

- SMWQueryProcessor::getParameters
  - SemanticMediaWiki – DocumentationParserFunction.php
  - SemanticMediaWiki – ResultPrintersTest.php
  - ...

- SMWQueryProcessor::getFormatParameters
  - SemanticMediaWiki – DocumentationParserFunction.php
  - SemanticMediaWiki – ParametersWidget.php

**Comment by kghbln** [comment]
This is not a blocking issue for the SMW 3.0.0 release. Thus this is for now rescheduled to be part of the SMW 3.1.0 release.
