### ISSUE TITLE
Move queryprinters - part I

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2740]
## Target release

3.0

## Issue

Move result (query) printers from `includes/queryprinters` to the namespaced `SMW\Query\Resultprinters` (i.e `/src`) target.

## Tasks

- [x] Move interface `SMW\ExportPrinter` to `SMW\Query\ExportPrinter`
- [x] Move interface `SMW\QueryResultPrinter` to `SMW\Query\ResultPrinter`
- [x] Move  `SMW\TableResultPrinter` to  `SMW\Query\ResultPrinters\TableResultPrinter`
- [x] Move  `SMW\ListResultPrinter` to  `SMW\Query\ResultPrinters\ListResultPrinter`
- [x] Move  `SMW\CategoryResultPrinter` to  `SMW\Query\ResultPrinters\CategoryResultPrinter`
- [ ] Move  `SMW\EmbeddedResultPrinter` to  `SMW\Query\ResultPrinters\EmbeddedResultPrinter`
- [x] Move  `SMW\FeedResultPrinter` to  `SMW\Query\ResultPrinters\FeedResultPrinter`
- [x] Move  `SMW\CsvResultPrinter` to  `SMW\Query\ResultPrinters\CsvResultPrinter`
- [ ] Move  `SMW\DsvResultPrinter` to  `SMW\Query\ResultPrinters\DsvResultPrinter`
- [ ] Move  `SMW\JsonResultPrinter` to  `SMW\Query\ResultPrinters\JsonResultPrinter`
- [ ] Move  `SMW\RdfResultPrinter` to  `SMW\Query\ResultPrinters\RdfResultPrinter`

Moved classes are expected to be aliased if referenced outside of SMW core to avoid breaking existing contracts.

**Comment by mwjames** [comment]
Just a note for those who want to pick one or two, the formatting of individual printers is less than ideal, if possible make sure to format the printer to increase readability with:

* public methods first
* protected methods second
* private last

Mark inherited methods with a comment block like below to allow a reader to be aware of its dependencies.

```
	/**
	 * @see ResultPrinter::getParamDefinitions
	 *
	 * {@inheritDoc}
	 */
```

**Comment by JeroenDeDauw** [comment]
@mwjames I think that is not ideal ordering. What I've been doing for some time now is arranging code to minimize vertical scrolling: have methods as close as possible after their first usage. If you have a class with two public methods, it might looks like this

* first public
* private used by first public
* private used by first public and second public
* private used by first public
* second public
* private used by second public
* private used by second public

I just discovered that PHPStorms "reformat" functionality allows rearranging code, and using default settings it actually does exactly what I had been doing manually. Quite stoked about this, since now I don't need to figure this out myself and can apply it with a few keystrokes to an entire project \o/

**Comment by mwjames** [comment]
> @mwjames I think that is not ideal ordering. What I've been doing for some
> time now is arranging code to minimize vertical scrolling: have methods as

New classes in SMW follow the pattern that supports a natural reading
flow which is public -> protected -> private, and not public ->
private  -> private -> protected -> private -> public ... and so on.

When reading a class I want to see the public interface first (not
scroll private methods in-between just to find the next public one),
protected are next to signal some possible inheritance mix-n-match,
and at last private classes that are invisible to the public consumer
hence found at very bottom.

I'm aware of [0] and the Clean Code story approach [0] but I find that
less accessible.

[0] https://stackoverflow.com/questions/1760850/best-practice-ordering-of-public-protected-private-within-the-class-definition

Cheers

**Comment by JeroenDeDauw** [comment]
Interesting to see another opinion on that topic.

Having thought about it a bit, it seems to me that ordering by access modifier has advantages in dirty code, though these largely evaporate in a more clean codebase. I'm thinking of writing a short blog on this :)

PS: you can use this PhpStorm rearrange without the ordering by usage, leaving just the access modifier ordering. So you can do what you described here automatically.

**Comment by kghbln** [comment]
The remaining query printers have been moved to a new task: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3512
