### ISSUE TITLE
Consolidate settings, config parameters

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2798]
It mostly relates to Boolean type settings where a feature switch achieves the same thing and allows in future to add more if necessary without cluttering the config matrix.

## Tasks

- [x] Browse settings `smwgBrowseFeatures` (`smwgToolboxBrowseLink`, `smwgBrowseShowInverse`, `smwgBrowseShowAll`, `smwgBrowseByApi`)
- [x] Category settings `smwgCategoryFeatures` (`smwgUseCategoryHierarchy`, `smwgCategoriesAsInstances`, `smwgUseCategoryRedirect`)
- [x] Parser settings `smwgParserFeatures` (`smwgInlineErrors`, `smwgEnabledInTextAnnotationParserStrictMode`, `smwgDecodeTextAnnotationWithStripMarker`, `smwgShowHiddenCategories`)

Thinking about mashing `smwgLinksInValues` into the parser setting since this is purely parser related.

@kghbln Early warning before you go all nuts on the upcoming changes.

PS: I was planning to push some changes in regards to the config parameter consolidation but with Travis being broken, that ain't gonna happen.

**Comment by kghbln** [comment]
Note to all. The deprecated configuration parameters will be removed with SMW 3.1.0!
