### ISSUE TITLE
2.5.6 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2996]
Date: 2018-02-14

* [2.5.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.x)
* [2.5.5... 2.5.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.5...2.5.x)

Refs: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2993

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
- [x] Copy release notes to `/docs/releasenotes/`
- [x] Update README.md in `/docs/`
- [x] Update COMPATIBILITY.md in `/docs/` (+ MW 1.30)
- [x] Update version number
  - [x] load.php
- [x] Create tag
- [x] Create tarballs
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Indicate alpha version of presumably upcoming release on 2.5.x branch
- [x] Add release docu to "master"
  - [x] Copy release notes to `/docs/releasenotes/`
  - [x] Update README.md in `/docs/releasenotes/`
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce on wiki 
- [x] Announce via mail (@JeroenDeDauw suggests to use series instead of branch. :)
- [x] Do a release tweet on Twitter
- [ ] In case no 2.5.7 release is done revert back the version info on the 2.5.x branch

**Comment by kghbln** [comment]
@mwjames Is there something else which could be back-ported? It is fine if that is not the case.

**Comment by ivanhercaz** [comment]
@kghbln, I will make the announce on wiki, based on the last release announcement.

**Comment by kghbln** [comment]
@ivanhercaz I was faster. :) However a Spanish translation ...

**Comment by ivanhercaz** [comment]
Yeaaah @kghbln! So fast and a coincidence that both we went to translate it hehe. I already translated the announcement to Spanish. One question, who manages Twitter?

**Comment by kghbln** [comment]
> One question, who manages Twitter?

Guess who. But I am not alone. @JeroenDeDauw is actually our grandmaster of twitter
