### ISSUE TITLE
Clean-up issue/pr tracker

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3084]
## Target release

3.0

## Issue

This is a reminder that by the time of the 3.0 release the issue tracker has been cleaned from any 3.0- issue.

## Tasks

- [ ] Remove any issue older than 90 days that hasn't seen any update within the mentioned time frame  
- [x] Close open PRs that are outdated or most likely will not see any update due to inactivity
- [x] Move enhancements, feature requests to the relevant project board and close those issues
- [x] Open bugs without an isolated, reproducible use case are to be closed

**Comment by mwjames** [comment]
https://probot.github.io/apps/stale/ is an Github app that closes stale issues and PRs.

**Comment by kghbln** [comment]
This was never really a true 3.0.0 task, however doing 3.0.0 was a great occasion to do just this: Clean up what is there. This is done now: all issues and pulls now have a target release not being 3.0.0 or are fairly new, bugs or tracking.
