### ISSUE TITLE
[Task 3.0] Create, improve test coverage for ElasticStore

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3165]
## Target release

3.0

## Issue

Create and improve coverage for the listed classes as a follow-up to #3054.

## Tasks

- [ ] includes/datavalues/SMW_DV_WikiPage.php
- [ ] maintenance/rebuildElasticIndex.php
- [ ] src/Deserializers/DVDescriptionDeserializer/DescriptionDeserializer.php
- [ ] src/Elastic/Admin/ElasticClientTaskHandler.php
- [ ] src/Elastic/Admin/IndicesInfoProvider.php
- [ ] src/Elastic/Admin/InfoProviderHandler.php
- [ ] src/Elastic/Admin/MappingsInfoProvider.php
- [ ] src/Elastic/Admin/NodesInfoProvider.php
- [ ] src/Elastic/Admin/SettingsInfoProvider.php
- [ ] src/Elastic/Connection/Client.php
- [ ] src/Elastic/Connection/ConnectionProvider.php
- [ ] src/Elastic/Connection/DummyClient.php
- [ ] src/Elastic/ElasticFactory.php
- [ ] src/Elastic/ElasticStore.php
- [ ] src/Elastic/Exception/InvalidJSONException.php
- [ ] src/Elastic/Exception/ReplicationException.php
- [ ] src/Elastic/Indexer/AttachmentAnnotator.php
- [ ] src/Elastic/Indexer/Bulk.php
- [ ] src/Elastic/Indexer/FileIndexer.php
- [ ] src/Elastic/Indexer/FileIngestJob.php
- [ ] src/Elastic/Indexer/Indexer.php
- [ ] src/Elastic/Indexer/IndexerRecoveryJob.php
- [ ] src/Elastic/Indexer/Rebuilder.php
- [ ] src/Elastic/Indexer/TextIndexer.php
- [ ] src/Elastic/QueryEngine/Condition.php
- [ ] src/Elastic/QueryEngine/DescriptionInterpreters/ClassDescriptionInterpreter.php
- [ ] src/Elastic/QueryEngine/DescriptionInterpreters/ConceptDescriptionInterpreter.php
- [ ] src/Elastic/QueryEngine/DescriptionInterpreters/ConjunctionInterpreter.php
- [ ] src/Elastic/QueryEngine/DescriptionInterpreters/DisjunctionInterpreter.php
- [ ] src/Elastic/QueryEngine/DescriptionInterpreters/NamespaceDescriptionInterpreter.php
- [ ] src/Elastic/QueryEngine/DescriptionInterpreters/SomePropertyInterpreter.php
- [ ] src/Elastic/QueryEngine/DescriptionInterpreters/ValueDescriptionInterpreter.php
- [ ] src/Elastic/QueryEngine/Excerpts.php
- [ ] src/Elastic/QueryEngine/FieldMapper.php
- [ ] src/Elastic/QueryEngine/QueryBuilder.php
- [ ] src/Elastic/QueryEngine/QueryEngine.php
- [ ] src/Elastic/QueryEngine/SearchResult.php
- [ ] src/Elastic/QueryEngine/SortBuilder.php
- [ ] src/Elastic/QueryEngine/TermsLookup.php
- [ ] src/Elastic/QueryEngine/TermsLookup/CachingTermsLookup.php
- [ ] src/Elastic/QueryEngine/TermsLookup/Parameters.php
- [ ] src/Elastic/QueryEngine/TermsLookup/TermsLookup.php
- [ ] src/Elastic/README.md
- [ ] src/MediaWiki/Hooks/HookRegistry.php
- [ ] src/Options.php
- [ ] src/Query/Excerpts.php
- [ ] src/Query/Language/ClassDescription.php
- [ ] src/Query/Language/Description.php
- [ ] src/Query/Language/Disjunction.php
- [ ] src/Query/Language/ThingDescription.php
- [ ] src/Query/Parser/LegacyParser.php
- [ ] src/Query/QueryComparator.php
- [ ] src/Services/SharedServicesContainer.php
- [ ] src/TypesRegistry.php

**Comment by kghbln** [comment]
Since ElasticStore is still experimental this is not a blocker for the upcoming 3.0.0 release. Thus I have for now moved this task to 3.1.0 Anyways this backend is being used on sandbox for months now without major issues.
