### ISSUE TITLE
2.5.7 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3185]
Date: TBD

* [2.5.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.x)
* [2.5.6... 2.5.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.5.6...2.5.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
- [x] Copy release notes to `/docs/releasenotes/`
- [x] Update README.md in `/docs/`
- [x] Update COMPATIBILITY.md in `/docs/` if applicable
- [x] Update version number
  - [x] load.php
- [x] Create tag
- [x] Create tarballs
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Indicate alpha version of presumably upcoming release on 2.5.x branch
- [x] Add release docu to "master"
  - [x] Copy release notes to `/docs/releasenotes/`
  - [x] Update README.md in `/docs/releasenotes/`
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce on wiki 
- [x] Announce via mail (@JeroenDeDauw suggests to use series instead of branch. :)
- [x] Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)
- [ ] In case no 2.5.8 release is done revert back the version info on the 2.5.x branch

**Comment by mwjames** [comment]
> @mwjames We have a couple of changes that may go public. If there are no objections I will try to do this

No objections.
