### ISSUE TITLE
Move queryprinters - part II

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3512]
## Target release

3.1.0

## Issue

Move result (query) printers from `includes/queryprinters` to the namespaced `SMW\Query\Resultprinters` (i.e `/src`) target.

## Tasks

- [x] Move  `SMW\EmbeddedResultPrinter` to  `SMW\Query\ResultPrinters\EmbeddedResultPrinter`
- [x] Move  `SMW\DsvResultPrinter` to  `SMW\Query\ResultPrinters\DsvResultPrinter`
- [x] Move  `SMW\JsonResultPrinter` to  `SMW\Query\ResultPrinters\JsonResultPrinter`
- [x] Move  `SMW\RdfResultPrinter` to  `SMW\Query\ResultPrinters\RdfResultPrinter`

Moved classes are expected to be aliased if referenced outside of SMW core to avoid breaking existing contracts.

## Reference
https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2740 - part I done for SMW 3.0.0
