### ISSUE TITLE
Hidden annotation with link in values not possible (SMW_PARSER_LINV)

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#3621]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.1
- PHP version: 7.2.10-0ubuntu0.18.04.1
- DB system (MySQL, Blazegraph, etc.) and version: 5.7.24-0ubuntu0.18.04.1

- `$smwgParserFeatures = SMW_PARSER_LINV;`
```
{
    "namespace": "SMW_NS_PROPERTY",
    "page": "Has text",
    "contents": "[[Has type::Text]]"
}
```
### Issue
Hidden annotation with link in values is not possible:
`[[Has text::[[Main Page]]| ]]`
results to "Main Page|" instead of a hidden annotation.

`{{#set:Has text=[[Main Page]]}}` works as expected adding a hidden annotation.

### Questions:
1. If this is not an intended use case, should I update the docu https://www.semantic-mediawiki.org/wiki/Help:Links_in_values, https://www.semantic-mediawiki.org/wiki/Help:$smwgLinksInValues with a hint to use #set for hidden annotation?
2. Would SemanticMediaWiki/tests/phpunit/Integration/JSONScript/TestCases/p-0449.json be the right place to add this test case?

**Comment by kghbln** [comment]
Thanks for bringing this up. I believe that it is save to say what `#set` needs to be used in this case and that in text annotations will not support this. @mwjames needs to confirm this though. Thus I added the "question" label for now.

ad 1) It indeed needs to be documented that `#set` is to be used. Apart from the links you stated I would also add an info to https://www.semantic-mediawiki.org/wiki/Help:Setting_values

ad 2) I guess test p-0444.json might even be the better place or a completely new test could be created to decouple things. @mwjames could hint here too.

**Comment by mwjames** [comment]
> {{#set:Has text=[[Main Page]]}} works as expected adding a hidden annotation.

This uses a different approach (it doesn't need to rely on the `LinksEncoder`).

> If this is not an intended use case,

It wasn't a supported use case but maybe adding the following line(s) will help with that.

```
@@ -226,10 +226,15 @@ class LinksEncoder {
 			LinksProcessor::getRegexpPattern( false ),
 			[ $parser, 'preprocess' ],
 			$match
 		) );

+		// Decode the pipe as part of a hidden marker (`...]]|`) to ensure that
+		// the standard MediaWiki parser can work its magic to hide the part of
+		// the string
+		$replace = str_replace( "&#x005D;&#x005D;&#124;", "&#x005D;&#x005D;|",  $replace );
+
```

## Tasks

- [ ] Confirm that above suggestion produces expected results
- [ ] Confirm that this doesn't introduce any regression for existing use cases
- [ ] Write integration test(s) with at least  (off the top of my head) coverage for (make sure to check for the output and value annotations to be expected):
  - `[[Has text::[[Has number::12]] [[Main Page]]| ]]`
  - `[[Has text::[[Has number::123| ]] [[Main Page]]| ]]`
  - `[[Has text::[[Has number::1234|Foo]] [[Main Page]]| ]]`
  - `[[Has text::[[Has number::12345| ]] [[Main Page]] ]]`
- [ ] Send a PR

As its modifies the parser logic, please confirm that it doesn't negatively influence the parsing performance (a simple before, after analysis should suffice, best to use MediaWiki's in-page `NewPP` limit report which outputs "[SMW] In‐text annotation parser time") by relying on two past examples (each for a single page):
  - https://gist.github.com/mwjames/a5d844c58d8806dcaa19ec13002442f2
  - https://gist.github.com/mwjames/78354d4b5d36878145dbcdee2a9daa75

**Comment by kghbln** [comment]
@mwjames Thanks for your input. So it seems that this was not originally intended to be supported. Since it does not seem to be too much of a pain to add support I relabel to "enhancement"

@gesinn-it It will be great if you could do the honours.

**Comment by gesinn-it** [comment]
@mwjames many thanks for your feedback. I'll test (+add test case) and send a PR

**Comment by kghbln** [comment]
While I was at it updating the docu for another reason I add [this, too.](https://www.semantic-mediawiki.org/w/index.php?title=Help:Links_in_values&diff=68463&oldid=68461)

**Comment by gesinn-it** [comment]
@mwjames @kghbln would it be possible to integrate this in 3.0.3 already?

**Comment by kghbln** [comment]
I am not sure if this is back-portable. However, I am currently pretty sure that we will not have a 3.0.3 if nothing unforeseen happens since 3.1.0 is ante portas.

**Comment by mwjames** [comment]
> I am not sure if this is back-portable.

Should be possible.

> I am currently pretty sure that we will not have a 3.0.3 if nothing unforeseen happens since 3.1.0 is ante portas.

Exactly, but here is the deal in case it is that important to you:

- Push the PR to the 3.0.x branch and make sure it passes the CI
- Create a ticket for a 3.0.3 release and then you (not @kghbln) go through all the necessary steps (just follow the checklist as done so for any other release) and make the required changes to create a small 3.0.3 feature release that just contains the mentioned PR

We normally don't backport features to a minor release but we are also not that fixed on not having community members a word in when and how a release happens, the only constraint is that @kghbln should only assist and not do any actual release work.
