### ISSUE TITLE
3.0.1 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3627]
Date: TBD

* [3.0.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.0.x)
* [3.0.0... 3.0.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.0.0...3.0.x)

## Tasks

- [ ] Update release notes
  - [ ] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
- [ ] Update INSTALL.md - not just version number
- [ ] Update composer.json
- [ ] Update version number
  - [ ] extension.json
  - [ ] COMPATIBILITY.md
- [ ] Create tag
- [ ] Update `semantic-mediawiki.org`
  - [ ] Run `composer update`
  - [ ] Touch `LocalSettings.php`
  - [ ] Update the SMW configuration
  - [ ] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [ ] Update version on wikidata, en, mw, and Free Software Directory
- [ ] Announce on wiki 
- [ ] Announce via mail (@JeroenDeDauw suggests to use series instead of branch. :)
- [ ] Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)
- [ ] In case no 2.5.8 release is done revert back the version info on the 2.5.x branch

**Comment by mwjames** [comment]
This morning I kicked down a couple of reported bugs, so you may want to look at them once merged.

**Comment by kghbln** [comment]
> This morning I kicked down a couple of reported bugs, so you may want to look at them once merged.

Cool, I will do the back-ports next week to avoid spamming the test queue with back-ports further.

**Comment by kghbln** [comment]
@mwjames This morning I did all the relevant back-ports to 3.0.x for me to do the release during next week.

**Comment by mwjames** [comment]
> @mwjames This morning I did all the relevant back-ports to 3.0.x for me to do the release during next week.

I'm leaving that for you decide when and how.

**Comment by kghbln** [comment]
> I'm leaving that for you decide when and how.

Thanks a lot. I will take advantage of this and do the release on Friday.
