### ISSUE TITLE
Hacking Semantic MediaWiki

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3799]
### Setup and configuration

- SMW version: all

### Issue

Issue to track changes to the documentation that can help developers (other than myself!!) to find a way around Semantic MediaWiki and how it can be "hacked" and extended.

#3768 contains the starting point that removed all (as far I could find) outdated developer documentation from the smw-wiki and moved an updated version of them to this repository while on-wiki only references are maintained to avoid having different documentations on different platforms.

[Hacking Semantic MediaWiki](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/architecture/README.md)
- Overview and explanations should go into https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/architecture
- Specific code examples should go into https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/docs/technical/code-snippets

### Tasks

- [ ] Find developer documentation on smw-wiki and create a list of potential moveable content
  - Absolute outdated documentation should remain on-wiki but be moved to the archive namespace
- [ ] Verify and move
  - [ ] Move the documentation
  - [ ] Create reference link on-wiki

**Comment by kghbln** [comment]
This is part of the the documentation project.
