### ISSUE TITLE
3.0.2 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3857]
Date: 2019-04-02

* [3.0.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.0.x)
* [3.0.1... 3.0.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.0.1...3.0.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
  - [x] Add RELEASE-NOTES to /docs/releasenotes/
- [x] Update /docs/README
- [x] Update INSTALL - not just version number
- [x] Update composer.json
- [x] Update version number
  - [x] extension.json
  - [x] COMPATIBILITY
- [x] Create tag
- [x] Provide release information to master
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce on wiki 
- [x] Announce via mail (use series instead of branch as wording)
- [x] Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)
- [ ] In case no 3.0.3 release is done revert back the version info on the 3.0.x branch

**Comment by kghbln** [comment]
@mwjames Admittedly I have not looked at the work you have done during the last two weeks. :( If there is something hat could go into this release via a back-port, just notify me about it via the pull. Will do the backports as a result.
