### ISSUE TITLE
Finialize list of features and supplementary functions

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4125]
To help users unfamiliar with SMW to find features and supplementary functions which are normally not enabled by default, I created [0] as starting point.

I would appreciate if some people from the community find the time to finalize and complete the list.

## Tasks

- [ ] Identify features and supplementary functions
- [ ] Add separate summary sections to the `smw@wiki` and link to the relevant on-wiki documentation
- [ ] After the list nears its completion, add [0] to the sidebar in order for users to easily find the entry point

[0] https://www.semantic-mediawiki.org/wiki/Features_and_supplementary_functions

**Comment by mwjames** [comment]
@krabina Do you think you can coordinate with @kghbln either before or during SMWCon to take a crack on this to finish up that part of the documentation?
