### ISSUE TITLE
3.1.1 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#4351]
Date: 2019-11-13

* [3.1.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.x)
* [3.1.0... 3.1.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.0...3.1.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
  - [x] Add RELEASE-NOTES to /docs/releasenotes/
- [x] Update /docs/README
- [x] Update INSTALL - not just version number
- [x] Update composer.json
- [x] Update version number
  - [x] extension.json
  - [x] COMPATIBILITY
- [x] Create tag
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce on wiki 
- [x] Announce via mail (use series instead of branch as wording)
- [x] Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)
- [ ] In case no 3.1.2 release is done revert back the version info on the 3.1.x branch

Things to include/backport:

* https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4332
* https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4333

**Comment by JeroenDeDauw** [comment]
@kghbln thoughts on doing this soon?

**Comment by kghbln** [comment]
> Things to include/backport:

Both were back-ported last week by me.

> thoughts on doing this soon?

Wanted to do this last week already however ... Scheduled for Wednesday.

**Comment by gesinn-it** [comment]
I'll try to submit a PR for  #4348 today. Can we add this to the 3.1.1 roadmap?

**Comment by mwjames** [comment]
> I'll try to submit a PR for  #4348 today. Can we add this to the 3.1.1
> roadmap

This cannot be part of a patch release. It would alter a significant
code path which hasn't been tested and requires some diligence in
crafting the change therefore shouldn't be deployed with a 3.1.x
release.

Generally https://semver.org/ applies unless of course the developer
is supper confident that his/her changes are beyond approach.

**Comment by JeroenDeDauw** [comment]
Agree with James, enhancements should not go into a patch release.

If you want the enhancement to become available soon then push for 3.2.0 to be released soon.

**Comment by kghbln** [comment]
> Wanted to do this last week already however ... Scheduled for Wednesday.

I am sorry for the delay. I had two medical emergencies this week, so I spent the time at the doctors.
