### ISSUE TITLE
3.1.2 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4372]
Date: 2019-12-19

* [3.1.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.x)
* [3.1.1... 3.1.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.1...3.1.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
  - [x] Add RELEASE-NOTES to /docs/releasenotes/
- [x] Update /docs/README
- [x] Update INSTALL - not just version number
- [x] Update composer.json
- [x] Update version number
  - [x] extension.json
  - [x] COMPATIBILITY
- [x] Create tag
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Update [roadmap](https://www.semantic-mediawiki.org/wiki/Roadmap) if applicable
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce on wiki 
- [x] Announce via mail (use series instead of branch as wording)
- [x] Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)
- [ ] In case no 3.1.3 release is done revert back the version info on the 3.1.x branch

**Comment by JeroenDeDauw** [comment]
11-13?

**Comment by kghbln** [comment]
> 11-13?

Copied from the previous task. Updated now.

**Comment by kghbln** [comment]
I was pretty sick over the holidays. Plan to do it tomorrow.

**Comment by mwjames** [comment]
> I was pretty sick over the holidays. Plan to do it tomorrow.

First of all, please make sure you take care of yourself, and
secondly, if people need a release they can provide assistance. You
don't have feel an obligation to do a release that doesn't fit your
volunteer time frame.

**Comment by JeroenDeDauw** [comment]
Agree, no need to rush this patch release.
