### ISSUE TITLE
3.1.3 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4443]
Date: 2020-01-23

* [3.1.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.x)
* [3.1.2... 3.1.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.2...3.1.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
  - [x] Add RELEASE-NOTES to /docs/releasenotes/
- [x] Update /docs/README
- [x] Update INSTALL - not just version number
- [x] Update composer.json
- [x] Update version number
  - [x] extension.json
  - [x] COMPATIBILITY
- [x] Create tag
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Update [roadmap](https://www.semantic-mediawiki.org/wiki/Roadmap) if applicable
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce on wiki 
- [x] Announce via mail (use series instead of branch as wording)
- [x] Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)
- [ ] In case no 3.1.4 release is done revert back the version info on the 3.1.x branch
