### ISSUE TITLE
3.1.4 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4444]
Date: 2020-02-12 - tentative

* [3.1.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.x)
* [3.1.3... 3.1.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.3...3.1.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
  - [x] Add RELEASE-NOTES to /docs/releasenotes/
  - [x] Update /docs/releasenotes/README
- [x] Update INSTALL - not just version number
- [x] Update composer.json
- [x] Update version number
  - [x] extension.json
  - [x] COMPATIBILITY
- [x] Create tag
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Update [roadmap](https://www.semantic-mediawiki.org/wiki/Roadmap) if applicable
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce on wiki 
- [x] Announce via mail (use series instead of branch as wording)
- [x] Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)
- [ ] In case no 3.1.4 release is done revert back the version info on the 3.1.x branch

**Comment by kghbln** [comment]
@mwjames I am wondering if the changes to make 3.2.0 ready for MW 1.34 could be pack-ported to bring support already in 3.1.4 Since 3.2.0 is due only in May 2020 where is quite a gap to bridge.

**Comment by mwjames** [comment]
> I am wondering if the changes to make 3.2.0 ready for MW 1.34 could be pack-ported

I made them in a way that should make is possible.
- #4394 for the Travis setup
- #4470 for the revision issue
- #4473 to ensure remaining test will pass on 1.34+

**Comment by JeroenDeDauw** [comment]
Could also just do 3.2.0 sooner.

**Comment by kghbln** [comment]
> I made them in a way that should make is possible.

Great, will pack-port during the week an switch s-mw.o to `3.1@dev`

**Comment by kghbln** [comment]
> Could also just do 3.2.0 sooner.

I am tying to establish a half-yearly release cycle. No need for a premature 3.2.0. Moreover the other semantic extensions need to be fluffed too.

**Comment by mwjames** [comment]
> #4473 to ensure remaining test will pass on 1.34+

To get the MW 1.34 CI green, I think you need https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/029d52233d603599663ff77368e9fd6ef9a0ea2e#diff-10eafd8bf5fbdde867b86fe38d30b9bb as well.

**Comment by kghbln** [comment]
> To get the MW 1.34 CI green, I think you need 029d522#diff-10eafd8bf5fbdde867b86fe38d30b9bb as well.

Thanks for the note. In case you have other back-ports this weekend, please just give me a ping. I will probably do a new release next week.

**Comment by akuckartz** [comment]
:rocket:
