### ISSUE TITLE
3.1.5 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4519]
Date: 2020-02-29 - tentative

* [3.1.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.x)
* [3.1.4... 3.1.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.4...3.1.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
  - [x] Add RELEASE-NOTES to /docs/releasenotes/
  - [x] Update /docs/releasenotes/README
- [x] Update INSTALL - not just version number
- [x] Update composer.json
- [x] Update version number
  - [x] extension.json
  - [x] COMPATIBILITY
- [x] Create tag
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Update [roadmap](https://www.semantic-mediawiki.org/wiki/Roadmap) if applicable
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce on wiki 
- [x] Announce via mail (use series instead of branch as wording)
- [x] Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)
- [ ] In case no 3.1.5 release is done revert back the version info on the 3.1.x branch

**Comment by mwjames** [comment]
As always, thanks for the effort and time.

**Comment by kghbln** [comment]
> As always, thanks for the effort and time.

Well, I have to thank you for the programming and help. I will for now not create a new milestone for 3.1.6 until we have a change to back-port.
