### ISSUE TITLE
Make 3.2.0 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4549]
Tracking issue for the 3.2.0 release.
- Release notes
- [Open issues for 3.2.0](https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestone/34)
- [3.2.0 issues already closed](https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestone/34?closed=1)
- Changes since 3.2.0
- Contributors since 3.1.0 https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2694#issuecomment-333473589

## 3.2.0 [rc.1](https://semver.org/#spec-item-11)

Tagged on 2020-09-05

## SMW 3.2.0 - 2020-09-07

- [x] Finalize rel notes (include contributors (`git shortlog -sn 3.1.0...3.2.0`)
  - [x] Add missing stuff tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues?q=label%3Areleasenotes+is%3Aclosed)
  - [x] Check [open issues](https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestones/SMW%203.1.0)
- [x] Update version number (3.1.0)
  - [x] extension.json
  - [x] README.md in `/`
  - [x] README.md in `/docs/`
  - [x] COMPATIBILITY.md (release date etc.)
  - [x] INSTALL.md
- [x] Create branch
- [x] Create tag
- [ ] Update https://github.com/SemanticMediaWiki/IndividualFileRelease: https://github.com/SemanticMediaWiki/IndividualFileRelease/pull/9
- [ ] Update "extension.json" (new alpha version)
- [x] Announce on wiki
- [x] Add release to [Wikidata](https://www.wikidata.org/wiki/Q20728)
- [x] Update version on en, mw, wikiapiary, fsd
- [x] Update [roadmap](https://www.semantic-mediawiki.org/wiki/Roadmap)
- [ ] Announce via mail
- [ ] Do a release tweet on Twitter
- [x] Close milestone
- [x] Update project
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
  - [x] Update [release template](https://www.semantic-mediawiki.org/wiki/Template:SMW_release_main_page)

### Possible blockers
- https://github.com/onoi/shared-resources/issues/3
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4830 - to be mentioned in an extra e-mail to community, change unrelated to this release.

**Comment by kghbln** [comment]
[Target compatibility](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md#platform-compatibility-and-release-status)
- PHP 7.1.0 - 7.4.0
- MW 1.31.0 - 1.35.x

**Comment by mwjames** [comment]
> PHP ... 7.4.0

Should be possible.

> MW ... 1.35.x

I think this going to be tough, I don't know what's going on MW master (haven't looked at it for 6 months) but [0] shows a lot of changes to interfaces and methods and I don't get the feeling this will be an easy ride (of course, I could be wrong!).

So, anyone wants to see this happen should work towards that goal early on and don't count on me to be the shining white knight for the last minute spurt.

[0] https://github.com/wikimedia/mediawiki/commits/master

**Comment by kghbln** [comment]
> I think this is going to be tough, I don't know what's going on MW master (haven't looked at it for 6 months) but [0] shows a lot of changes to interfaces and methods and I don't get the feeling this will be an easy ride (of course, I could be wrong!).

This will be cool and I really hope that it will not be an effort to big.

> So, anyone wants to see this happen should work towards that goal early on and don't count on me to be the shining white knight for the last minute spurt.

You know reality. I guess we will have a Corona cure first.

**Comment by mwjames** [comment]
> I think this is going to be tough, I don't know what's going on MW master

#4568 is the last in a series of changes to make SMW ready for running with PHPUnit 8.5 which is required by MW master since https://github.com/wikimedia/mediawiki/commit/2d6923b76cd6c8012cead93e84f1de649b876b70.

**Comment by akuckartz** [comment]
No pressure from me, but are there any updates regarding the intended Dates?

**Comment by kghbln** [comment]
> No pressure from me, but are there any updates regarding the intended dates?

My intention was to do the release around the release of MW 1.35 for admins to be able to migrate both core and smw at the same time.

> EDIT: MW 1.35 is still delayed due to Corona:

Indeed, this is what is causing the delay here. Since there is no branch point for 1.35 yet all sorts of unpleasant changes can still be done. Thus is no point in claiming compat with 1.35 since we cannot exactly assess what  will be happening.

I think the date for the branch point will be announced this month or next month. We can see from there.

**Comment by akuckartz** [comment]
An updated schedule was published by the WMF today:
> The first step is cutting the release branch, REL1_35, which will occur on Monday, July 13.

> We will then be in "pencils down" mode: developers will stop targeting MediaWiki 1.35 for new features. Instead, any new features would continue to be applied to master and would target MediaWiki 1.36 or later. The only work that would continue towards MediaWIki 1.35 would be blockers - critical bug fixes or features close to completion that need to make it into the release. This would happen by merging those patches into master and then backporting them to the REL1_35 branch.

> We anticipate that MediaWiki 1.35 will be released at the beginning of August.

https://lists.wikimedia.org/pipermail/mediawiki-l/2020-June/048402.html

**Comment by kghbln** [comment]
So this time we are getting breaking changes till a fortnight prior to the release basically with no alpha period. I come to conclude that it was a mistake to wait for MW 1.35 and try to make SWM compatible.

I will try to create the RELEASE NOTES soon.

**Comment by akuckartz** [comment]
Maybe this should be raised in the MW Stakeholders group.

**Comment by kghbln** [comment]
No, does not matter since thing will not change anyways. Just hope that all of this gets predicable again and consequently also a SMW release schedule. Let's call it COVID confusion.

**Comment by akuckartz** [comment]
MediaWiki 1.35.0-rc.1 is ready for testing:
https://lists.wikimedia.org/pipermail/mediawiki-l/2020-August/048457.html

**Comment by JeroenDeDauw** [comment]
I was about to reply to the post on the mailing list by saying that we are waiting on the MW 1.35 release. Then I came here since I do not see any reason why we would do that given that we've not been fixing MW 1.35 compat issues. 

Here is what I think we should do: release 3.2 as the mess it is (release wise) and then switch to a model where changes need to be documented in their commits or shortly after. People are of course free to contribute and deal with the mess, but this has not happened in the last half year. Postponing things forever makes things worse.

**Comment by akuckartz** [comment]
@JeroenDeDauw 
> we've not been fixing MW 1.35 compat issues.

Which are these issues that *must* be resolved so that SMW is usable with MW 1.35?

**Comment by JeroenDeDauw** [comment]
Perhaps I should have qualified that a bit more. We did fix some MW 1.35 issues - there just was no concerted effort to get all the way to MW 1.35 compat.

I've actually been running SMW master and MW master and have not spotted any issues except a bunch of deprecation warnings in the logs. That was on development wikis so far from covers all SMW functionality.

To say SMW is compatible with MW 1.35 we need to have the tests pass. Which they don't at the moment. Some of which could be due to brittle tests, so no issues with the actual production code. And some of which could be due to deprecation warnings and notices, that while bad, won't break your site if you turn them off.

**Comment by akuckartz** [comment]
Which of these issues can be moved to SMW 3.3.0 ?https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestone/34

**Comment by JeroenDeDauw** [comment]
None of them look required for doing a release now

Yes, it's be great if they got done. But they are not. And they can easily be included in a 3.2.1 release. Or a 3.3 one if we don't take a year between releases.

**Comment by JeroenDeDauw** [comment]
@akuckartz you added a bunch of extra stuff to the milestone. Opposite of what I would have done.

What about we do an RC release right now. And then the 3.2.0 release in a week (without forcing ourselves to magically come up with comprehensive release notes)?

**Comment by akuckartz** [comment]
@JeroenDeDauw I briefly reviewed all open issues and assigned all those to 3.2 which I think deserve a closer look. But I am not against moving them into the future.

**Comment by JeroenDeDauw** [comment]
I will create a release candidate this weekend and do the 3.2.0 release next week.

**Comment by akuckartz** [comment]
Closing this issue seems to be premature. Most of the subtasks are without a check mark.

**Comment by QUN-com** [comment]
#
