### ISSUE TITLE
Make 3.1.6 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4672]
Date: 2020-04-19

* [3.1.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.x)
* [3.1.5... 3.1.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.1.5...3.1.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
  - [x] Add RELEASE-NOTES to /docs/releasenotes/
  - [x] Update /docs/releasenotes/README
- [x] Update INSTALL - not just version number
- [x] Update composer.json
- [x] Update version number
  - [x] extension.json
  - [x] COMPATIBILITY
- [x] Create tag
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Update [roadmap](https://www.semantic-mediawiki.org/wiki/Roadmap) if applicable
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce on wiki 
- [x] Announce via mail (use series instead of branch as wording)
- [x] Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)
- [x] Close milestone
- [x] Update project
- [ ] In case no 3.1.6 release is done revert back the version info on the 3.1.x branch

**Comment by kghbln** [comment]
@mwjames If you have something that could be back-ported, please do point me to it. Thanks.

**Comment by mwjames** [comment]
> @mwjames If you have something that could be back-ported, please do point me to it. Thanks.

We should consider #4648 because I saw #4669 where a user created `SMW/Schema:Seqmap` page with the `PROPERTY_PROFILE_SCHEMA` having a title_prefix` rule which is enforced by [0, 1] but somehow the schema validation didn't kick in.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/3.1.x/data/schema/property-profile-schema.v1.json#L20-L27
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/3.1.x/src/MediaWiki/Content/SchemaContent.php#L422-L424

**Comment by kghbln** [comment]
> We should consider #4648 because I saw #4669 where a user created 

Thanks for the note. Yeah, will do. If there is something else ...

**Comment by kghbln** [comment]
@mwjames I'd like to do the release either this evening or tomorrow. Something "nice" to back-port?
