### ISSUE TITLE
Make 3.2.1 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4886]
Date: 2020-11-21

* [3.2.x branch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.2.x)
* [3.2.0... 3.2.x](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/3.2.0...3.2.x)

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
  - [x] Add RELEASE-NOTES to /docs/releasenotes/
  - [x] Update /docs/releasenotes/README
- [x] Update INSTALL - not just version number
- [x] Update composer.json
- [x] Update version number
  - [x] extension.json
  - [x] COMPATIBILITY
- [x] Create tag
- [x] Update `semantic-mediawiki.org`
  - [x] Run `composer update`
  - [x] Touch `LocalSettings.php`
  - [x] Update the SMW configuration
  - [x] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Update [roadmap](https://www.semantic-mediawiki.org/wiki/Roadmap) if applicable
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [ ] Announce on wiki 
- [ ] <s>Announce via mail (use series instead of branch as wording)</s>
- [ ] <s>Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)</s>
- [ ] Close milestone
- [x] Update project
