### ISSUE TITLE
Make the 4.0.2 realease

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5248]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestone/47

## Tasks

- [x] Update release notes
  - [x] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
  - [x] Add RELEASE-NOTES to /docs/releasenotes/
  - [x] Update /docs/releasenotes/README
- [x] Update INSTALL - not just version number
- [x] Update composer.json
- [x] Update version number
  - [x] extension.json
  - [x] COMPATIBILITY
- [x] Create tag
- [ ] Update `semantic-mediawiki.org`
  - [ ] Run `composer update`
  - [ ] Touch `LocalSettings.php`
  - [ ] Update the SMW configuration
  - [ ] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [x] Update [roadmap](https://www.semantic-mediawiki.org/wiki/Roadmap) if applicable
- [x] Update version on wikidata, en, mw, and Free Software Directory
- [x] Announce on wiki 
- [ ] <s>Announce via mail (use series instead of branch as wording)</s>
- [ ] <s>Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)</s>
- [x] Close milestone
- [x] Update project
