### ISSUE TITLE
Make the x.y.z realease

### ISSUE THREAD

**Issue by mnoo4577** [SemanticMediaWiki/SemanticMediaWiki#5468]
## Tasks

- [@mnoo4577] Update release notes
  - [@mnoo4577] Add missing commits tagged with [releasenotes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+is%3Aopen+label%3Areleasenotes)
[] Add RELEASE-NOTES to /docs/releasenotes/
  - [x] Update /docs/releasenotes/README
- [x] Update INSTALL - not just version number
- [x] Update composer.json
- [x] Update version number
  - [x] extension.json
  - [x] COMPATIBILITY
- [x] Create tag
- [x] Update `semantic-mediawiki.org`
  - [ ] Run `composer update`
  - [ ] Touch `LocalSettings.php`
  - [ ] Update the SMW configuration
  - [ ] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [ ] Update [roadmap](https://www.semantic-mediawiki.org/wiki/Roadmap) if applicable
- [ ] Update version on wikidata, en, mw, and Free Software Directory
- [ ] Announce on wiki 
- [ ] <s>Announce via mail (use series instead of branch as wording)</s>
- [ ] <s>Do a release tweet on Twitter (Also mention if it is a feature, maintenance or security release)</s>
- [ ] Close milestone
- [ ] Update project

Added ONOI_HTTP_REQUEST_RESPONSECACHE_PREFIX and ONOI_HTTP_REQUEST_RESPONSECACHE_TTL
Deprecated CachedCurlRequest::setCachePrefix and CachedCurlRequest::setExpiryInSeconds
Deprecated CachedCurlRequest::isCached in favor of CachedCurlRequest::isFromCache
@Mnoo4577
