### ISSUE TITLE
2.1.0 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#635]
This issue is to coordinate the SMW 2.1.0 release.

Open issues: https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestones/SMW%202.1

Changes so far: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/RELEASE-NOTES.md

--

RC1 target: week of January 5th

* [x] Finalize rel notes
* [x] Update version number
 * [x] SemanticMediaWiki.php
 * [x] README.md
 * [x] COMPATIBILITY.md
* [x] Check Special:Version
* [x] Run `composer update` for smw.o
* [x] Create tag
* [x] Create tarballs
* [x] Announce via mail
* [x] Do a release tweet on Twitter

--

Release target: week of January 19th

* [x] Finalize rel notes
* [x] Update version number
 * [x] SemanticMediaWiki.php
 * [x] README.md
 * [x] COMPATIBILITY.md
* [x] Check Special:Version
* [x] Create tag
* [x] Create tarballs
* [x] Update release template
* [x] Run `composer update` for smw.o
* [x] Announce on wiki
* [x] Update version on wikidata, en, de, mw and wikiapiary
* [x] Touch LocalSettings.php
* [x] Announce via mail
* [x] Do a release tweet on Twitter

**Comment by JeroenDeDauw** [comment]
I've just updated the target date to something that suits me.

Are there any remaining blockers for the release? What about #649?

**Comment by mwjames** [comment]
> Are there any remaining blockers for the release? What about #649?

#649 isn't an issue (or more precisely is fixed) but #682 is and needs to be fixed first.

**Comment by JeroenDeDauw** [comment]
Why #682? This is not a regression since one of the last releases no?

**Comment by mwjames** [comment]
> Why #682? This is not a regression since one of the last releases no?

You are right, this is not a regression (exists from the early start of `SQLStore3`) therefore moving it to 2.2.

**Comment by JeroenDeDauw** [comment]
@mwjames does the [compat doc](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md) need any updates for 2.1?

**Comment by JeroenDeDauw** [comment]
@mwjames why smw.org not to MW 1.24.x?

@kghbln What does RTP mean?

**Comment by mwjames** [comment]
> why smw.org not to MW 1.24.x?

This is also fine.

**Comment by kghbln** [comment]
In the [compat docs](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/00e3f99de8b6985be0462aeb613926d5ed918552/docs/COMPATIBILITY.md#recent-releases) SMW 1.7.x, 1.8.x are still listed as legacy releases which would me that security support is still provided. Is this still the case? If not it should rather say obsolete release. Not sure how much effort is still put into 1.9.x ...

**Comment by kghbln** [comment]
Done this: https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/3f0275bfb60948bdc585f9a1255fbb4807d3ce57 OK?

**Comment by JeroenDeDauw** [comment]
We are not supporting anything before 2.0. `Legacy release` means that it is not supported and no longer getting security fixes.

**Comment by kghbln** [comment]
This is very different from what MW does where legacy means supported with security fixes. I think that the wording should be the same here.

**Comment by JeroenDeDauw** [comment]
@mwjames is 4store support still beta?

**Comment by JeroenDeDauw** [comment]
SMW wiki is now running the RC. I have not updated MW yet as this is more cumbersome with the skin hacker we have going on

**Comment by mwjames** [comment]
> @mwjames is 4store support still beta?

I once got 4store running on Travis (somewhere I have the PR) but as long as it is not officially run on Travis I think it can only be declared as beta.

**Comment by JeroenDeDauw** [comment]
I have done another pass at the release notes. Next step: make tag. Can someone +1 first?

**Comment by mwjames** [comment]
Discussion from d3ef330acb427a7c085da6ea54ec8d481df47021

> Yeah I know. That is what the standard dictates as well. And it's what I've started doing elsewhere.
> I take it that you thus want 2.1.0?

I think as release tag you want to be precise such as 2.1.0 but as product you just want to refer to it as 2.1 (including all possible bug-fixes 2.1.*).

**Comment by JeroenDeDauw** [comment]
Tarballs have been created. @kghbln can you double check this is all fluff? https://sourceforge.net/projects/semediawiki/files/semediawiki/Semantic%20MediaWiki%202.1%20RC1/

**Comment by plegault3397** [comment]
4store with the latest updates is working for me without any problems.

**Comment by JeroenDeDauw** [comment]
@plegault3397 thanks a lot for the feedback!

**Comment by mwjames** [comment]
Just added Travis/openrdf-sesame 2.7.14 service support (#707)

**Comment by kghbln** [comment]
:( May hard drive failed on me Saturday morning after 19 months of cheerful service. Spent the whole weekend recovering from the mess since I also had to change the OS. Still trying to fluff up the situation ...

@JeroenDeDauw Yeah, the file release looks good to me.

**Comment by mwjames** [comment]
* [x] #710 fixed

**Comment by JeroenDeDauw** [comment]
No issues where reported for the RC as far as I know. Any objections against releasing 2.1 (based on the already existing 2.1.x git branch)

**Comment by JeroenDeDauw** [comment]
Master is no at 2.2 alpha, and the 2.1 release notes have been moved to https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-2.1.0.md

**Comment by JeroenDeDauw** [comment]
I've now created the 2.1.0 tag

**Comment by kghbln** [comment]
Cool. I am just fluffing up the installation page. A worry still is that we cannot presend RELEASE NOTES on the wiki due to the GitHub extension issue. Perhaps [this extension](https://www.mediawiki.org/wiki/Extension:MarkdownExtraGeshiSyntax) is a workaround for the time being. Thus I will be able to add md between tags and we would even get tocs back. This extension needs fluff in the long run.

**Comment by JeroenDeDauw** [comment]
I'll have a look at the GH extension. It's not even showing the file now it's been moved...

**Comment by kghbln** [comment]
Cool, meanwhile I will do the tarballs.

**Comment by kghbln** [comment]
Well, it is a pleasure to see the work you all put into this release! You rock an all levels!

**Comment by JeroenDeDauw** [comment]
Hope you are talking to @mwjames  - he did most of the work :)

The GH extension is working fine for me locally. I do not know why nothing shows up on SMW wiki.

**Comment by kghbln** [comment]
Indeed I do. What about touching LocalSettings.php?

**Comment by JeroenDeDauw** [comment]
Ok, so looks like I found what is going wrong. The extension is making a call to Http:get (Http being a MediaWiki class). On SMW wiki it is correctly getting `https://raw.githubusercontent.com/SemanticMediaWiki/SemanticMediaWiki/master/docs/releasenotes/RELEASE-NOTES-2.1.0.md`, yet it is returning an empty string.

**Comment by JeroenDeDauw** [comment]
Same result when I use file_get_contents. Perhaps this is some dumb stuff like someone that randomly decided to block outgoing requests from the server?

**Comment by JeroenDeDauw** [comment]
@kghbln you can haz https://semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.1.0

**Comment by kghbln** [comment]
I ain't no see nothing. Instruct on how to see.

**Comment by JeroenDeDauw** [comment]
What. It went away again :<0

**Comment by kghbln** [comment]
Yeah. :(

**Comment by JeroenDeDauw** [comment]
Oh wait - this silly composer thing downgraded the extension to before I changed the URL...

**Comment by JeroenDeDauw** [comment]
It's running the latest version of the extension again, though it is still not showing up. I guess I'll have to debug the thing again to see what is happening. Will do so tomorrow.

**Comment by JeroenDeDauw** [comment]
Ah, second issue is that apparently the request always fails when using MediaWikis HTTP class. Works fine when using `file_get_contents` though (see https://github.com/JeroenDeDauw/GitHub#102-2015-01-20). Fixed now on the server.

**Comment by JeroenDeDauw** [comment]
All fluff for release announce now?

**Comment by kghbln** [comment]
Just added the last fluff. Go for it!

**Comment by JeroenDeDauw** [comment]
> Just added the last fluff.

Where? Is this something I should be aware of for the rel announce?

**Comment by kghbln** [comment]
No, just cosmetics.

**Comment by kghbln** [comment]
@JeroenDeDauw Still one tweet to go! Who removed the twitter icon on main page of smw.o if it was ever there.

**Comment by JeroenDeDauw** [comment]
o_O The Twitter logo is back with a vengeance!

![wat](https://cloud.githubusercontent.com/assets/146040/5856485/dba8788c-a243-11e4-85e5-4a08b0b27d4c.jpg)

**Comment by JeroenDeDauw** [comment]
Haha @kghbln, how did you not see that? :D

![say-hi-to-fluffy](https://cloud.githubusercontent.com/assets/146040/5856526/4b601180-a244-11e4-94f1-7b76d1cecabd.jpg)

**Comment by kghbln** [comment]
:) Twitter returned with a bang. :) This really is fluffy with a bit of grumpy I guess. :D

**Comment by mwjames** [comment]
@kghbln I think that the smw@docu in some areas need to be checked whether it contains the correct content compared to the release notes (e.g. `\;` escaping for records, regex queries like `[[Url::~http://*query=*]] OR [[Url::~*ccc*]]` for SQLStore and SPARQLStore etc.)

https://semantic-mediawiki.org/wiki/Examples/Queries/Uri_type_regex_query
