### ISSUE TITLE
2.1.2 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#888]
- [x] #882 / 9f43fda3ae9
- [x] #887 / 7b0f1fb993
- [x] #897 / eef691ae6

**Comment by JeroenDeDauw** [comment]
@mwjames what is the goal of this issue? Collecting fixes we want to have backported?

**Comment by mwjames** [comment]
> Collecting fixes we want to have backported?

Exactly

**Comment by JeroenDeDauw** [comment]
Given it's been two months since 2.1 and there already being a bunch of new features for 2.2, why not simply go for 2.2 instead?

**Comment by mwjames** [comment]
> why not simply go for 2.2 instead?

There is a bunch of stuff the needs fixing/clean-up first before the 2.2 label can be put on. (I got sidetracked with the whole `import from` fix up).

**Comment by mwjames** [comment]
@JeroenDeDauw @kghbln I copied over the changes (see #920 with #882 fixing the issue).

**Comment by kghbln** [comment]
So let's go for 2.1.2 today?

**Comment by JeroenDeDauw** [comment]
No objections from my side

**Comment by kghbln** [comment]
So here we go:
- [ ] increment and tag version after RELEASE NOTES are done
- [ ] composer update on smw.o
- [ ] create file release and publish on sf
- [ ] add a news item on swm.o
- [ ] do a release tweet

**Comment by JeroenDeDauw** [comment]
@mwjames can you do the rel notes?

**Comment by mwjames** [comment]
> can you do the rel notes?

b6739ff1ed5

**Comment by kghbln** [comment]
@mwjames Since Jeroen is off on a secret mission ;) could you do the second step. Apart from updating smw.o we could finish this one.

**Comment by mwjames** [comment]
> could you do the second step. Apart from updating smw.o we both could finish this one.

Here you go: https://github.com/SemanticMediaWiki/SemanticMediaWiki/releases/tag/2.1.2

**Comment by kghbln** [comment]
Thank you! All done but the smw.o update.

**Comment by JeroenDeDauw** [comment]
I'll update it soonish, but this is going to be to latest master, not 2.1.x., since I see no reason to use the later

**Comment by kghbln** [comment]
As long as we have a somewhat recent version running imho all is in fluff ... :)

**Comment by JeroenDeDauw** [comment]
Updated now

**Comment by kghbln** [comment]
:+1:
