### ISSUE TITLE
2.2 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#912]
Tracking issue for the 2.2 release.

* [Release notes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/RELEASE-NOTES.md)
* [Open issues for 2.2](https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestones/SMW%202.2)
* [2.2 issues already closed](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues?q=milestone%3A%22SMW+2.2%22+is%3Aclosed)
* [Changes since 2.1](https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.1.0...master)

--

RC1 target: April 24th

* [x] Finalize rel notes
* [x] Update version number
 * [x] SemanticMediaWiki.php
 * [x] COMPATIBILITY.md
* [x] Create tag
* [x] Create tarballs
* [x] Announce via mail
* [x] Do a release tweet on Twitter

--

Release target: week of May 4th

* [x] Finalize rel notes
* [x] Update version number
 * [x] SemanticMediaWiki.php
 * [x] README.md
 * [x] COMPATIBILITY.md
* [x] Check Special:Version
* [x] Create tag
* [x] Create tarballs
* [x] Update release template
* [x] Run `composer update` for smw.o
* [x] Announce on wiki
* [x] Update version on wikidata, en, de, mw and wikiapiary
* [x] Touch LocalSettings.php
* [x] Announce via mail
* [ ] Do a release tweet on Twitter

**Comment by JeroenDeDauw** [comment]
@mwjames what are the blockers?

**Comment by JeroenDeDauw** [comment]
I'd like to ditch the `doctrine/dbal` dependency for the release if we do not actually start using it properly.

**Comment by mwjames** [comment]
>  what are the blockers?

There are some stuff that's need fixing first and as long as I stumble onto things I haven't planned to fix but needs fixing in order to move on (remove aux-modifier usage in `SPARQLStore`, small Exporter performance improv., add monolingual datatype to be able to define multilingual property labels, some renaming, I got a PR for #682 (but needs other tests before),  #753 + #870 + #869 + #895 needs fixing) I'm not prepared to push the button for 2.2.

> I'd like to ditch the doctrine/dbal dependency for the release

Fine with me.

PS: I really want to focus on something new but each time I write a test I find a legacy issue which really drives me nuts.

**Comment by JeroenDeDauw** [comment]
Thanks for explaining. I much appreciate you looking into these issues. It is however not clear to me how they are blockers. These are not recent regressions or are they? If they are not, a 2.2 released without addressing them will still be better than the existing 2.1 release, and not delay the fixes, since they can just go into 2.3 or 2.2.1 when they are ready.

**Comment by kghbln** [comment]
> I'd like to ditch the `doctrine/dbal` dependency for the release if we do not actually start using it properly.

That's cool since this [breaks my automated updating](https://gist.github.com/kghbln/6f4c03a4ec2e99d30547) every fortnight. Of course only if we are not loosing anything here. Totally up to you. I will manage to ungrump myself. :)

**Comment by JeroenDeDauw** [comment]
Ping @mwjames

**Comment by JeroenDeDauw** [comment]
I'm feeling ignored now...

**Comment by mwjames** [comment]
> I'm feeling ignored now...

I hope not, github spams me with messages ... that I hardly follow through.

The main objective of moving the QueryEngine has been finalized (more or less) therefore from that point of view there shouldn't be any show stoppers.

**Comment by JeroenDeDauw** [comment]
Ok, so how about doing the RC as soon as we can and then doing the rel a week later if no issues show up?

**Comment by mwjames** [comment]
> Ok, so how about doing the RC as soon as we can and then doing the rel a week later if no issues show up?

:+1: 

We should probably kill the dbal stuff as we currently make no use of it.

**Comment by mwjames** [comment]
As a sidenote, some tests beyond `master@5cc1f1d` (1.25 alpha) fail because of #607, [0] / #790 / #960 therefore we can't make any statement about the support of 1.25 (released version) as we only confidently test until MW `master@5cc1f1d`.

[0] https://phabricator.wikimedia.org/T89307

**Comment by JeroenDeDauw** [comment]
That's quite annoying. However, it seems the test is failing due to an issue in MediaWiki, and not broken SMW behaviour. Hence, can we not simply disable it for 1.25+ or change it in such a way that it only tests the intended SMW behaviour and thus not break? It'd suck a lot to decrease the amount of compat we have.

**Comment by JeroenDeDauw** [comment]
I've created a `2.2.x` branch now. Now sure this is the name we should use, perhaps it ought to be `2.2.x-dev`. http://stackoverflow.com/questions/29807813/should-one-include-the-dev-suffix-for-branches-that-are-not-stable-yet

Anyway, like this we can continue with 2.3.0 development on master during the 2.2.0 RC process. Also, this allows us to kill the DBAL dependency on the branch and keep it on master. I've already done this in cc524a4a263e3a24dcc8877a5b41688d07a8daea, probably ought to have submitted a PR into the branch though...

**Comment by JeroenDeDauw** [comment]
Are the rel notes fluff? Once they are I can create the tag.

**Comment by kghbln** [comment]
Sorry for being very much inactive during the past two weeks. I am working on finally getting rid of SMW 1.8 on the last five wikis. Lesson learned: Do not change or add features when you just want to migrate to a new version since it just slows down migration. Currently I do not see a worry for this release.

**Comment by mwjames** [comment]
> Currently I do not see a worry for this release.

It still needs some rigid hand-to-hand combat testing (man-to-machine or woman-to-machine, opposed to the continued automatic testing that already occurs).

Since we can actually semi-simulate an input of a user [0, 1] and compare it against an expected result we can cover more use cases to reduce the chance for regressions but it needs a combined effort to actual define those scenarios,

I'd like to invite @SemanticMediaWiki/testers to find use cases that are not yet covered, which can be generalized and transformed it into something like [1] in order to run it against the CI environment (it does not require any dev-experience but some diligence in defining the boundaries and expected results). 

The more cases we have the higher is the confidence that we have not add any regressions (it doesn't make them unlikely, it only diminishes its probability). 

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests#write-integration-tests-using-json-script

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/Query/Fixtures/format-02-02-table-output-en.json

**Comment by kghbln** [comment]
> Are the rel notes fluff?

I found #851 not to be in there and added this to both branches (master and 2.2.x). Hope that this is the correct procedure

**Comment by JeroenDeDauw** [comment]
@kghbln it was already there, though with different, more user orientated, description: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/RELEASE-NOTES.md#enhancements

**Comment by JeroenDeDauw** [comment]
> It still needs some rigid hand-to-hand combat testing

That is precisely what the RC release is for. Better first create it and then ask people to test it.

**Comment by JeroenDeDauw** [comment]
I've now created the `2.2.0-RC1` tag.

**Comment by kghbln** [comment]
> @kghbln it was already there

Oops, and I was sure to have looked for the issue id. Don't tell anyone I "messed up". ;)

> I think that in general we could do a better job at making the features, enhancements and bugfixes more understandable.

What's basically why I added a link to the page explaining this. However a bit more prose in the release file does indeed not hurt.

> I've now created the 2.2.0-RC1 tag. @kghbln can you do the tarballs?

[Done](https://sourceforge.net/projects/semediawiki/files/semediawiki/Semantic%20MediaWiki%202.2%20RC1/), will do the tweet now.

**Comment by kghbln** [comment]
Tweet done together with a link to the call for testing. @JeroenDeDauw You can now do the mail. :)

**Comment by JeroenDeDauw** [comment]
@mwjames the tripple store compat info in COMPATIBILITY.md needs to be added for 2.2.x.

**Comment by JeroenDeDauw** [comment]
Any objections against tagging 2.2?

**Comment by mwjames** [comment]
> Any objections against tagging 2.2?

Not really but I'm not sure whether someone has really tested the RC or not! @kghbln ?

> tripple store compat info in COMPATIBILITY.md needs to be added for 2.2.x.

Done.

For the sake of completeness, I run 4store 1.1.4 [0] and Virtuoso 7.1 [1] on Travis yesterday (4store failed unexpected on two new test cases while Virtuoso 7.1 passed together with all the others). I haven't looked at the 4store 1.1.4 test issue but since all other stores pass I do blame 4store. 

[0] https://travis-ci.org/mwjames/SemanticMediaWiki/builds/61200454
[1] https://travis-ci.org/mwjames/SemanticMediaWiki/builds/61203319

**Comment by kghbln** [comment]
> Not really but I'm not sure whether someone has really tested the RC or not!

I am afraid that I did not do extra testing so far. :( Any of our @SemanticMediaWiki/testers ?

Currently I have an enormous backlog. At the same time you are doing so many cool changes and improvements. It's hard to keep pace here.

> Any objections against tagging 2.2?

Cannot do any release fluffiness tomorrow so I personally opt for May 7. Also have to look if I more or less already documented the improvements on wiki.

**Comment by mwjames** [comment]
Here you can see the failures [0] occurring when running our tests against the latest MW 1.25/1.26 with (e.g "ApiResult::getData was deprecated in MediaWiki 1.25.", "Use of ApiBase::getResultData was deprecated in MediaWiki 1.25", "Use of WikiImporter::__construct without a Config instance was deprecated in MediaWiki 1.25" etc.).

I'm neither amused nor inclined to fix those just because WMF has decided it needs to break extensions and create workload for volunteers.

FAILURES!
Tests: 3025, Assertions: 7988, Errors: 5, Failures: 10, Skipped: 9.

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/61403931

**Comment by JeroenDeDauw** [comment]
I unexpectedly need to attend some conference abroad... so I probably can't get to this in the next few days.

**Comment by kghbln** [comment]
No worries. Gives me more time to finish the docu on wiki. Should take this chance to get my act together here.

**Comment by JeroenDeDauw** [comment]
Well never mind that, apparently I do have the time.

**Comment by JeroenDeDauw** [comment]
git shortlog -sn 2.0...2.1.0|wc -l
    11

vs

    git shortlog -sn 2.1.0...2.2.x|wc -l
    17

:)

**Comment by kghbln** [comment]
:+1: Still working on the docu

**Comment by kghbln** [comment]
@JeroenDeDauw The major changes are now more or less documented. So no hold-up for the mail. Just hau it raus! Will do he Tweet afterwards. The release notes are now showing properly too.

**Comment by JeroenDeDauw** [comment]
Mail send

**Comment by kghbln** [comment]
Tweet done!
